- .env
- Makefile
> Moved registry to dockerhub

- docs/user/setup.rst
sbt handles its own versions and compiler interfaces
> Inaccurate requirement

- README.rst
- docs/introduction/index.rst
Add reference to SDSC in README (issue #72) and add security warnings (issue https://github.com/SwissDataScienceCenter/renga-documentation/issues/7)
> Docs erbou

- docker-compose.yml
https://github.com/SwissDataScienceCenter/renga-graph/pull/21 will break current docker-compose.
This is required to fix it.
> Set play application secret on navigation too

- Makefile
- README.rst
* fix wrong test script path in readme
* change to https for the default repo basepath in the makefile
> docs: update test script path

- docs/developer/index.rst
- docs/developer/web.rst
> Docs api spec

- docker-compose.yml
- services/logging/renga_python_logging.yml
* add python logging config
* remove links --> it appears these are no longer needed
> Python logging

- .travis.yml
- README.rst
- docs/developer/code_repo_structure.rst
> docs: remove tutorial page from links and update README

- .editorconfig
- Makefile
* use the same branch across the repos to build images
* add makefile-services
addresses #121
> adapt makefile to build new images

- README.rst
> fix readme typo and add link to dev on renga-python

- docker-compose.yml
Resolves #129 
To do: disable lfs and remove associated volume
> [WIP] Added volumes for services

- README.rst
- docs/index.rst
- docs/introduction/index.rst
- docs/user/development-note.rst
- docs/user/firststeps.rst
- docs/user/setup.rst
Provide some basic instructions for the development branch that are in sync with the recent changes. 
---
addresses #135 
closes #140
> docs: sync basic instructions

- charts/renga/values.yaml
> Fix nginx body size limit

- charts/renga/charts/ui/templates/deployment.yaml
- charts/renga/charts/ui/values.yaml
- Updated pull image policy for ui
- Updated probes for ui
> Updated the ui chart

- .travis.yml
- Makefile
- docs/introduction/index.rst
- docs/spelling_wordlist.txt
- docs/user/firststeps.rst
- pytest.ini
- scripts/run-tests.sh
- scripts/travis-install.sh
- scripts/wait-for-services.sh
- tests/requirements.txt
- tests/test_apispec.py
- tests/test_renga.py
start adding some integration tests
---
addresses #135 https://github.com/SwissDataScienceCenter/renga/issues/146
> add integration tests

- charts/renga/charts/gitlab/templates/deployment.yaml
- charts/renga/charts/redis/templates/_helpers.tpl
- charts/renga/charts/redis/templates/networkpolicy.yaml
> Added network policy for redis

- docker-compose.yml
- services/gitlab/Auto-DevOps.gitlab-ci.yml
- services/jupyterhub/jupyterhub_config.py
- services/jupyterhub/project_service.py
- services/jupyterhub/spawners.py
- services/notebook/Dockerfile
- services/notebook/gitlab-commit-push.js
- services/notebook/gitlab_commit_push.py
- services/notebook/install
- services/notebook/notebook.json
- services/notebook/setup.py
> jupyterhub: checkout correct branch on DockerSpawner

- services/jupyterhub/spawners.py
This should fix the problems with readonly checkouts. 
@ciyer and/or @ableuler can you please test?
> notebook: fix readonly checkout

- charts/renga/charts/ui/templates/deployment.yaml
- charts/renga/charts/ui/values.yaml
- docker-compose.yml
Merge after https://github.com/SwissDataScienceCenter/renga-ui/pull/178
> ui: use nxing based image

- services/jupyterhub/Dockerfile
- services/jupyterhub/jupyterhub_config.py
- services/notebook/Dockerfile
> Jupyterhub 0.8.1

- services/jupyterhub/spawners.py
closes #203 
contingent on #201
> use V1Container model

- docker-compose.yml
- services/jupyterhub/Dockerfile
- services/jupyterhub/jupyterhub_config.py
- services/jupyterhub/project_service.py
- services/jupyterhub/spawners.py
This closes #192 (pulls alpine/git). 
There is still the problem of a timeout on server spawn. See #210. 
---
addresses #186
> pull alpine/git in docker spawner

- tests/test_renga.py
merge this and cherry pick this commit in the other PRs to fix failing tests
> fix failing test with new UI image

- docker-compose.yml
- services/gitlab/Auto-DevOps.gitlab-ci.yml
- services/singleuser/Dockerfile
> jh: fix singleuser image tag

- charts/renku/templates/configmap.yaml
Solves issue with deploying with domain name and HTTPS -> post-install job fails.
> Fix pot-install job

- README.rst
- docker-compose.yml
- services/jupyterhub/spawners.py
fixing some minor (but potentially breaking!) naming/configuration problems.
> Config patch

- .travis.yml
- charts/README.rst
- charts/renku/templates/post-install-job.yaml
> Fix post-install hook

- charts/README.rst
- charts/renku/values.yaml
- docker-compose.yml
Pass JUPYTERHUB_URL to UI through docker-compose.yml. Merge before https://github.com/SwissDataScienceCenter/renga-ui/pull/203
> JUPYTERHUB_URL to UI

- Makefile
- scripts/run-tests.sh
- tests/conftest.py
- tests/test_renku.py
This adds clicking through to the "Launch Notebook" button to the test.
Note: this will probably continue failing until at least the first part of #223 is fixed. 
closes https://github.com/SwissDataScienceCenter/renku/issues/195
> Integration test

- services/jupyterhub/requirements-k8s.txt
- services/jupyterhub/spawners.py
- services/notebooks/Dockerfile
- services/notebooks/notebooks_service.py
- services/notebooks/requirements.txt
> make dns-compliant server names

- Makefile
- services/notebooks/notebooks_service.py
> notebooks: use "-" as escape character

- services/jupyterhub/spawners.py
> jh: install git-lfs before repo checkout

- charts/minikube-values.yaml
- charts/renku/templates/configmap.yaml
- charts/renku/values.yaml
> demo user not gitlab admin

- charts/renku/templates/configmap.yaml
The value was hard-coded, not using the proper env var
> Fix GitLab sudo token in post-install-job

- services/jupyterhub/spawners.py
> Fix #261: include CI_REPOSITORY_URL in the container environment

- scripts/run-tests.sh
- services/jupyterhub/spawners.py
- tests/test_renku.py
addresses #263 by checking for the `image_build` job in the spawner.
> jh: spawner checks for image_build jobs

- services/jupyterhub/spawners.py
> jh: use username in all containers and volumes

- services/jupyterhub/spawners.py
> jh: enforce lowercase image names

- services/jupyterhub/spawners.py
> jh: initialize submodules in the init container

- charts/renku/templates/configmap.yaml
Job will error if postgres databases already exist
> Fix postgresql script fail

- docs/requirements.txt
See: https://readthedocs.org/projects/renku/builds/7463593/
Happened after #283
> Fix docs build on RTD

- charts/renku/templates/registry-secret.yaml
> fix registry secret when on port 443

- charts/renku/templates/configmap.yaml
> fix https in post-install-gitlab

- services/jupyterhub/spawners.py
> jh: detect canceled job status

- services/jupyterhub/spawners.py
> Updated default single user image to include renku

- charts/renku/charts/gitlab/templates/_gitlab.rb.tpl
> Disabled rack-attack

- docs/developer/minikube.rst
> [Docs] Added pipenv install step to minikube setup

- Makefile
- charts/README.rst
- charts/keycloak/templates/_renku-realm.tpl
- charts/renku/Chart.yaml
- charts/renku/requirements.yaml
- charts/renku/templates/_helpers.tpl
- charts/renku/templates/ingress.yaml
- charts/renku/values.yaml
- docker-compose.yml
- docs/developer/index.rst
- docs/developer/minikube.rst
- docs/developer/services/api_gateway.rst
- scripts/minikube_deploy.py
- services/keycloak/docker-entrypoint.sh
- services/keycloak/renku-realm.json.tpl
Closes #313 
Makefile / docker-compose setup of renga is ready for the proxy, don't merge until work on the proxy is finished.
Merge after: https://github.com/SwissDataScienceCenter/renku-gateway/pull/20
Merge together with https://github.com/SwissDataScienceCenter/renku-ui/pull/228
> Integrate renku-gateway

- .travis.yml
- charts/renku/templates/configmap.yaml
- docker-compose.yml
- scripts/renku-start.sh
Fixes [minikube] deployments after #341
> Fix demo user mapping in gitlab after #341

- .travis.yml
> ci: no deploy on cron jobs

- charts/README.rst
- charts/chartpress.yaml
- charts/gitlab/templates/_gitlab.rb.tpl
- charts/gitlab/templates/ssh-nodeport-service.yaml
- charts/gitlab/values.yaml
- charts/minikube-values.yaml
- charts/renku/requirements.yaml
- docs/developer/minikube.rst
Closes #352 
~~TODO: clean to publish chart~~
> Modified GitLab setup for ssh port

- services/jupyterhub/spawners.py
- services/singleuser/Dockerfile
- services/singleuser/git-config.bashrc
> JH: make renku CLI work

- services/singleuser/git-config.bashrc
Quote values to avoid syntax errors
> Fix git-config.bashrc

- scripts/run-tests.sh
- services/singleuser/Dockerfile
Use git lfs < 2.5, as it causes problems with GitLab: https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/20923
> Hold on git lfs

- charts/renku/requirements.yaml
- services/jupyterhub/jupyterhub-k8s.Dockerfile
> jh: bump base image version

- charts/renku/values.yaml
> jh: make pod culling time 24 hours

- charts/renku/requirements.yaml
Bumping dependencies values
Taking today's latest.
> Charts: Update requirements.yaml

- tests/test_renku.py
Adapt test to renaming of notebooks in UI.
> Fix integration test

- charts/renku/values.yaml
Add a hint to values.yaml to the possibility of templating the ui welcome page from the renku charts.
> Add ui comment to values.yaml

- docs/_static/uml/gateway-sequence.uml
- docs/developer/services/api_gateway.rst
Add sequence diagram and more information to gateway section in developer docs.
> Update gateway section in developer docs

- docs/developer/setup.rst
> Add missing helm chart repo

- .travis.yml
Condition was likely removed due to a mistake in #344
> Do not deploy on CRON job

- charts/renku/requirements.yaml
was too quick earlier, forgot to update requirements...
> charts: use 0.2.0 renku dependencies

- scripts/travis-deploy.sh
> update gitlab chart during travis deploy

- .gitignore
- charts/gitlab/templates/_gitlab.rb.tpl
- charts/gitlab/templates/deployment.yaml
- charts/gitlab/templates/secret.yaml
- charts/gitlab/values.yaml
- charts/minikube-values.yaml
- charts/renku/templates/_renku-realm.tpl
- charts/renku/templates/configmap.yaml
- charts/renku/templates/post-install-job-gitlab.yaml
- charts/renku/templates/secrets.yaml
- charts/renku/values.yaml
Closes #447, closes #453
* Reworked gitlab secrets
* Reworked renku secrets
~~After this PR, all secrets should have a default value starting with `changeme` so that they are easily tracked.~~
This will probably need to be revisited after making sure subcharts follow the same principles.
> Rework charts secrets

- docs/user/lfs.rst
From lfs help:
```
$ g lfs pull -h
git lfs pull [options] [<remote>]
```
> Fix lfs docs

- Pipfile
- Pipfile.lock
> upgraded requests

- charts/renku/requirements.lock
- charts/renku/requirements.yaml
Use the deployed helm chart in `renku`
> Bump GitLab (2)

- charts/example-configurations/minikube-values-gitlab.yaml
- docs/developer/example-configurations/gitlab.rst
- docs/developer/example-configurations/index.rst
- docs/developer/index.rst
- docs/spelling_wordlist.txt
Add an example configuration for deploying Renku locally against gitlab.com and describe how to use it in the developer docs.
> Add an example configurations for using gitlab.com

- docs/conf.py
> Update conf.py (fix #489)

- Pipfile
- Pipfile.lock
- docs/developer/python_setup.rst
- docs/developer/setup.rst
- docs/spelling_wordlist.txt
> Developer setup documentation update

- CONTRIBUTING.rst
> Added guidelines for contributors

- docs/user/lfs.rst
Another useful git lfs command for fixing the repository after accidentally committing large data files
> git lfs migrate import

- charts/README.rst
- charts/minikube-values.yaml
- scripts/minikube_deploy.py
Just a fix for a small problem that I ran into when trying to deploy Renku locally on minikube. (Related to #550 )
> Fix minikube deployment

- docs/developer/setup.rst
> docs: updated developer docs

- docs/_static/uml/graph-create-hook-sequence.uml
- docs/_static/uml/graph-sync-events-sequence.uml
There were some changed done to the Graph Services processes. This PR updates the relevant sequence diagrams.
> Graph Services sequence diagrams update

- .travis.yml
- Pipfile
- Pipfile.lock
- scripts/travis-deploy.sh
One more fix for new travis behavior...
> build(ci): deploy tags

- .github/CODEOWNERS
Use the @SwissDataScienceCenter/kartografen for chart reviews.
> chore: use kartografen for chart reviews

- charts/renku/requirements.lock
This is a release to include UI `0.5.1`.
> build: update requirements for ui 0.5.1

- charts/example-configurations/minikube-values-gitlab.yaml
- charts/example-configurations/minikube-values-renkulab-template.yaml
- charts/minikube-values.yaml
- charts/renku/values.yaml
This introduces a new graph.jena.renkuuser.password property which is used to secure the Jena `renku` dataset endpoints.
> feat: renku dataset in Jena to be secured

- README.rst
This fixes the readme file. At the moment the output has a few glitches
> fix: readme output

- charts/example-configurations/minikube-values-gitlab.yaml
- charts/example-configurations/minikube-values-renkulab-template.yaml
- charts/renku/requirements.yaml
- charts/renku/templates/_helpers.tpl
- charts/renku/templates/ingress.yaml
- charts/renku/values.yaml
- docs/_static/graphviz/graph_services_architecture.dot
- docs/_static/graphviz/renku_architecture.dot
- docs/_static/uml/knowledge-graph-graphql-sequence.uml
- docs/developer/services/graph_services.rst
- docs/developer/services/index.rst
- docs/developer/services/services_architecture.rst
- docs/spelling_wordlist.txt
This PR introduces changes required for a new graph-service providing GraphQL endpoint. It also brings relevant documentation changes.
> graph-service to handle GraphQL queries

- charts/renku/values.yaml
https://github.com/SwissDataScienceCenter/renku-ui/issues/561 adds configuration settings that should be documented in the values.yaml file.
> Documentation for the renku project templates configuration

- charts/minikube-values.yaml
- charts/renku/requirements.lock
- charts/renku/requirements.yaml
- charts/renku/values.yaml
Update dependencies so the master branch is up-to-date.
> build: update dependencies to latest versions

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
#628 adds a release template - these are standard "user" issue templates
> chore: add standard issue templates

- charts/renku/values.yaml
- charts/values.yaml.changelog.md
Update the examples in `values.yaml` about `notebooks.serverOptions` according to the changes here https://github.com/SwissDataScienceCenter/renku-notebooks/pull/213/files
> chore: modify values example

- charts/renku/requirements.yaml
Change needed to be consistent with https://github.com/SwissDataScienceCenter/renku/pull/652
Tested by dev deployment
> Bumped version of gateway in requirements.yaml

- charts/values.yaml.changelog
- charts/values.yaml.changelog.md
* Merged `values.yaml.changelog` to `values.yaml.changelog.md`
* Added change needed for `remove realm template` PR
> Merged and updated changelog

- charts/renku/requirements.yaml
Version 0.20.0 of renku-graph services introduces the projects resource.
> Bumped version of renku-graph to 0.20.0

- charts/renku/requirements.yaml
This PR bumps the version of renku-graph to the latest (containing some bug fixes).
> Bumped version of renku-graph

- charts/renku/values.yaml
- charts/values.yaml.changelog.md
A few minor documentation improvements related to PR #647
> charts: Improve documentation of deployment changes

- charts/README.rst
Originally submitted by @jkremser as #578.
> minor(helm readme): use star instead of the exact version 

- docs/developer/contributing/api-guidelines.rst
fyi:
* https://www.rfc-editor.org/info/rfc5988
* https://www.rfc-editor.org/info/rfc8288
> adjust: RFC 5988 obsoleted by RFC 8288

- charts/gitlab/values.yaml
- charts/renku/Chart.yaml
- charts/renku/requirements.lock
- charts/renku/requirements.yaml
- charts/renku/values.yaml
Upgraded GitLab version to enable renaming a forked project.
> Release fix: GitLab version

- docs/developer/contributing/api-guidelines.rst
This PR updates API guidelines for the developers according to the agreement made on the Renku meeting.
> Updated the api-guidelines

- .github/ISSUE_TEMPLATE/bug_report.md
> feat: add info to bug report template

- .github/workflows/automerge.yml
> added test

- .github/workflows/pull-request-test.yml
Fix an invalid namespace name on pr-deploy.
> chore: set a valid namespace name

- actions/publish-chart/Dockerfile
- actions/publish-chart/README.md
- actions/publish-chart/action.yml
- actions/publish-chart/publish-chart.sh
- actions/update-component-version/Dockerfile
- actions/update-component-version/README.md
- actions/update-component-version/action.yml
- actions/update-component-version/update-upstream.sh
Adds an actions directory with generic re-usable actions. 
Two actions are added: 
* action to update a component version in the main renku chart
* action to build images and publish the chart with chartpress
closes #784
> build: add component update action

- charts/renku/requirements.lock
- charts/renku/requirements.yaml
- tests/README.md
- tests/src/test/scala/ch/renku/acceptancetests/LoginSpec.scala
- tests/src/test/scala/ch/renku/acceptancetests/model/users.scala
- tests/src/test/scala/ch/renku/acceptancetests/pages/LoginPage.scala
- tests/src/test/scala/ch/renku/acceptancetests/pages/Page.scala
- tests/src/test/scala/ch/renku/acceptancetests/pages/ProjectPage.scala
- tests/src/test/scala/ch/renku/acceptancetests/tooling/AcceptanceSpecData.scala
- tests/src/test/scala/ch/renku/acceptancetests/tooling/Grammar.scala
- tests/src/test/scala/ch/renku/acceptancetests/workflows/Login.scala
* Support the register a new user workflow (this is done with the register flag, see docs)
> Test improvements

- tests/src/test/scala/ch/renku/acceptancetests/HandsOnSpec.scala
- tests/src/test/scala/ch/renku/acceptancetests/pages/ProjectPage.scala
Adds a delay waiting for the environment to be ready.
> chore(tests): fix handson test

- README.rst
added links to discourse and gitter in the readme
> docs: add discourse and gitter links to README

- tests/src/test/scala/ch/renku/acceptancetests/HandsOnSpec.scala
- tests/src/test/scala/ch/renku/acceptancetests/pages/LandingPage.scala
- tests/src/test/scala/ch/renku/acceptancetests/pages/NewProjectPage.scala
- tests/src/test/scala/ch/renku/acceptancetests/pages/ProjectPage.scala
- tests/src/test/scala/ch/renku/acceptancetests/pages/TopBar.scala
Improvements to tests to make them more robust.
> Test robustness

- CHANGELOG.md
- charts/renku/requirements.lock
- charts/renku/requirements.yaml
- charts/renku/values.yaml
Release candidate requirements and preliminary release notes
> Requirements for new release

- charts/renku/requirements.lock
- charts/renku/requirements.yaml
We made a mistake in #853 and used the latest dev version of the UI - this PR sets it to `0.8.0`.
> chore: set ui version

- charts/renku/values.yaml
Fixes an error in the chart values.
> chore: fix duplicate value

- charts/renku/values.yaml
Comment out template repository version to allow inheriting the value from the UI values
> chore: comment out template values

- charts/renku/requirements.yaml
Update notebooks- and core dependency to latest versions.
> chart: manually update renku chart dependencies

- charts/renku/requirements.yaml
- tests/src/test/scala/ch/renku/acceptancetests/LoginSpec.scala
- tests/src/test/scala/ch/renku/acceptancetests/pages/GitLabPages.scala
- tests/src/test/scala/ch/renku/acceptancetests/pages/JupyterLabPage.scala
- tests/src/test/scala/ch/renku/acceptancetests/pages/LandingPage.scala
- tests/src/test/scala/ch/renku/acceptancetests/pages/LoginPage.scala
- tests/src/test/scala/ch/renku/acceptancetests/pages/NewProjectPage.scala
- tests/src/test/scala/ch/renku/acceptancetests/pages/Page.scala
- tests/src/test/scala/ch/renku/acceptancetests/pages/ProjectPage.scala
- tests/src/test/scala/ch/renku/acceptancetests/pages/ProjectsPage.scala
- tests/src/test/scala/ch/renku/acceptancetests/pages/WelcomePage.scala
- tests/src/test/scala/ch/renku/acceptancetests/tooling/Grammar.scala
- tests/src/test/scala/ch/renku/acceptancetests/tooling/TestsDefaults.scala
> tests: pages to report loaded status

- tests/src/test/scala/ch/renku/acceptancetests/HandsOnSpec.scala
- tests/src/test/scala/ch/renku/acceptancetests/MinimalFunctionalitySpec.scala
- tests/src/test/scala/ch/renku/acceptancetests/pages/ProjectPage.scala
- tests/src/test/scala/ch/renku/acceptancetests/tooling/Grammar.scala
- tests/src/test/scala/ch/renku/acceptancetests/workflows/Collaboration.scala
Acceptance test that creates a new issue.
> test: create a new issue

- .github/workflows/pull-request-teardown.yml
- .github/workflows/pull-request-test.yml
~~Work in progress, currently blocked by RBAC problems with Rancher-generated users.~~
PR now working and ready for review. Entire life-cycle - including teardown - seems to work.
> ci: activate anonymous notebooks in ci deployments

- charts/deploy-tmp-notebooks.py
- tests/src/test/scala/ch/renku/acceptancetests/tooling/AnonEnv.scala
- switch to an existing project in test.
- fix bug in deployment script for anonymous sessions.
> fix ci tests

- .github/workflows/deploy.yml
> ci: store screenshots on CD deployment test failure

- charts/chartpress.yaml
- charts/gitlab/Chart.yaml
- charts/gitlab/templates/_gitlab.rb.tpl
- charts/gitlab/values.yaml
- charts/renku/requirements.yaml
- charts/renku/values.yaml
Note that the gitlab 0.5.1 chart has already been built and published manually.
> Update gitlab chart

- tests/src/test/scala/ch/renku/acceptancetests/tooling/Grammar.scala
> Make tests more robust to delays in KG building.

- docs/tutorials/first_steps/03_python_environment.rst
- docs/tutorials/first_steps/06_create_workflow.rst
> docs: fix typo and broken link

- docs/user/how_to_documentation.rst
- docs/user/index.rst
- docs/user/templates.rst
Removes a page that made reference to "Ku"s 😱
> docs: remove unused doc page

- .github/workflows/deploy.yml
The acceptance tests were fixed in #1389 for the pull requests. This PR uses the same logic in the deploy action test
> ci: fix acceptance test on deploy

- docs/user/templates.rst
Requires https://github.com/SwissDataScienceCenter/renku-python/pull/1509 to be merged
> chore: update documentation for automated template updates.

- .github/workflows/auto-reqs-update-pr.yml
> fix: do not create duplicate auto PRs

- .github/workflows/deploy.yml
> chore: update name of acceptance-tests directory in deploy.yml

- acceptance-tests/.gitignore
- acceptance-tests/README.md
- acceptance-tests/docker-run-tests.sh
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/BatchRemoveProjectSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/ExistingProjectSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/MinimalFunctionalitySpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/GitLabPages.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/NewProjectPage.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/ProjectPage.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/ProjectsPage.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/BatchRemoveProjectSpecData.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/ExistingProjectSpecData.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/Grammar.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/Collaboration.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/RemoveProject.scala
Test to create a new merge request
Closes #1185
> test: create a new merge request

- charts/renku/requirements.yaml
> chore: bump renku-core version to 0.11.2

- charts/deploy-tmp-notebooks.py
- charts/renku/values.yaml
This should be merged only after [this commit](https://github.com/SwissDataScienceCenter/renku-notebooks/commit/7fe32c5c8241641d467ba5bb0d07f085d87384e6) is referenced in the chart requirements.
> chore: clean default nb values

- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/FlightsTutorial.scala
- charts/renku/requirements.yaml
- docs/tutorials/first_steps/02_add_data.rst
- docs/tutorials/first_steps/06_create_workflow.rst
Updates renku-core to 0.12.0 and adapts the tests and tutorial docs.
> chore: update to renku-core 0.12.0 and update docs/tests 

- acceptance-tests/src/test/scala/ch/renku/acceptancetests/DatasetModificationFlowSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/model/datasets.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/DatasetPage.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/ProjectPage.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/Grammar.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/Datasets.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/FlightsTutorial.scala
> Acceptance tests to verify dataset modification flows

- acceptance-tests/README.md
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/ProjectPage.scala
Update to support UI changes SwissDataScienceCenter/renku-ui#1123
> Fix acceptance tests

- docs/developer/example-configurations/gitlab.rst
fix link to Renkulab's GitLab.
> chore: fix link in developer documentation to correct values file

- CHANGELOG.rst
- charts/renku/requirements.yaml
Downgrading notebooks, since the latest version has a bug.
> fix: patch 0.7.3 release

- docs/developer/setup.rst
Fix reference to old charts directory.
> docs: Fix developer setup readme

- .github/workflows/deploy.yml
- actions/deploy-renku/entrypoint.sh
This PR does the CD using the `deploy-dev-renku`script.
~~Note that it is currently configured to run from the branch of this PR for testing - once it works I'll switch the branch requirements on the workflow.~~
See [here](https://github.com/SwissDataScienceCenter/renku/actions/runs/499768279) for a successful deploy - acceptance tests are failing, but that seems to be a problem in general and not related to this PR. 
addresses #1631
> chore: modify CD workflow for deployment script

- .github/workflows/pull-request-test.yml
> fix(ci): re-enable anonymous sessions for ci

- .github/workflows/deploy.yml
- .github/workflows/pull-request-test.yml
- acceptance-tests/Dockerfile
- acceptance-tests/README.md
- acceptance-tests/docker-run-tests.sh
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/AcceptanceSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/AnonEnv.scala
- actions/deploy-renku/deploy-dev-renku.py
- actions/deploy-renku/entrypoint.sh
- helm-chart/renku/templates/tests/test-renku.yaml
- helm-chart/renku/values.yaml
- pyproject.toml
> chore: update CD branch with latest changes from master

- .github/workflows/pull-request-test.yml
- actions/download-test-artifacts/Dockerfile
- actions/download-test-artifacts/action.yml
- actions/download-test-artifacts/entrypoint.sh
> feat: refactor download artifacts in its own action.

- acceptance-tests/README.md
- helm-chart/renku/values.yaml
And some more information to use the S3 bucket when using `helm test`.
> Add S3 parameters placeholder in default values.yml.

- .github/workflows/deploy.yml
- actions/update-component-version/update-upstream.sh
- helm-chart/renku/requirements.yaml
- run CD deployment from master
- let auto-update PRs be created against master
- merge development into master
/deploy
> Close development branch

- CHANGELOG.rst
- helm-chart/renku/Chart.yaml
- helm-chart/renku/requirements.yaml
- helm-chart/renku/values.yaml
> 0.7.5 renku release

- .github/workflows/deploy.yml
I was pretty sure I had changed this before, but... 🤷‍♂️
> chore: fix CD by using correct branch

- helm-chart/renku/templates/post-install-job-keycloak.yaml
/deploy
Duplicate of #1923 (to make CI deployment in a new PR)
> fix: post-install-keycloak job

- CHANGELOG.rst
> chore: release 0.7.6

- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/ProjectsPage.scala
- helm-chart/renku/requirements.yaml
> chore: update renku-ui version to 0.11.5

- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/ProjectPage.scala
- helm-chart/renku/requirements.yaml
> chore: update renku-ui version to 0.11.6

- .github/workflows/pull-request-test.yml
- helm-chart/README.rst
- helm-chart/renku/requirements.yaml
- helm-chart/renku/templates/_keycloak-clients-users.tpl
- helm-chart/renku/templates/configmap.yaml
- helm-chart/renku/templates/ingress.yaml
- helm-chart/renku/templates/keycloak-password-secret.yaml
- helm-chart/renku/templates/keycloak-postgres-secret.yaml
- helm-chart/renku/templates/post-install-job-keycloak.yaml
- helm-chart/renku/templates/secrets.yaml
- helm-chart/renku/values.yaml
- helm-chart/values.yaml.changelog.md
- scripts/init-realm/requirements.txt
/deploy
~(still work in progress, but I want a CI deployment)~ ready for review now!
> chore: upgrade keycloak dependency

- acceptance-tests/README.md
- acceptance-tests/build.sbt
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/DatasetModificationFlowSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/HandsOnSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/PrivateProjectSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/ProjectPage.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/AcceptanceSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/GitLabApi.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/Grammar.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/KnowledgeGraphApi.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/RestClient.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/Collaboration.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/Datasets.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/JupyterNotebook.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/RemoveProject.scala
> refactor: various acceptance tests improvements

- acceptance-tests/README.md
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/AnonymousEnvironmentSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/BatchProjectRemovalSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/DatasetModificationSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/HandsOnSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/JupyterNotebookForPrivateProjectSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/MergeRequestsAndIssuesSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/ProjectForkingSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/ProjectSettingsModificationSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/AcceptanceSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/GitLabApi.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/RestClient.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/Collaboration.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/Datasets.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/JupyterNotebook.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/Project.scala
> Acceptance tests feature oriented

- CHANGELOG.rst
- helm-chart/renku/Chart.yaml
> Prep release 0.7.8

- acceptance-tests/src/test/scala/ch/renku/acceptancetests/model/datasets.scala
> fix: flaky dataset free-text search test

- acceptance-tests/src/test/scala/ch/renku/acceptancetests/FreeTextDatasetSearchSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/model/datasets.scala
> test: flaky free-text dataset search spec

- helm-chart/renku/requirements.yaml
This is not an automated pull request.
/deploy
> chore: updating renku-core version to 0.14.1

- CHANGELOG.rst
- docs/requirements.txt
- docs/spelling_wordlist.txt
- helm-chart/renku/Chart.yaml
- helm-chart/renku/values.yaml
> chore: prep Renku 0.7.9

- helm-chart/renku/values.yaml
Add community templates to the RenkuLab template list.
/deploy
> chore: include community templates

- CHANGELOG.rst
- docs/spelling_wordlist.txt
- helm-chart/renku/Chart.yaml
- helm-chart/renku/values.yaml
> chore: prep 0.7.10

- acceptance-tests/build.sbt
- acceptance-tests/project/plugins.sbt
> fix: temporarily remove license header dep until new host found

- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/LoginPage.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/Page.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/ProjectPage.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/Environments.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/Login.scala
> fix: tests to work on non-DEV envs

- helm-chart/renku/requirements.yaml
> chore: update ui and ui-server version to 0.11.11

- CHANGELOG.rst
- docs/spelling_wordlist.txt
- helm-chart/renku/Chart.yaml
- helm-chart/renku/values.yaml
> chore: prep 0.7.11

- helm-chart/renku/requirements.yaml
> chore: update renku-notebooks to 0.8.11

- CHANGELOG.rst
- helm-chart/renku/Chart.yaml
> Prep 0.7.12

- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/Login.scala
> fix(tests): allow redirection to other hosts during tests

- helm-chart/example-configurations/minimal-values.tmpl
- helm-chart/renku/templates/_keycloak-clients-users.tpl
- helm-chart/renku/values.yaml
- helm-chart/values.yaml.changelog.md
> feat(chart): add renku-cli client to keycloak

- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/Grammar.scala
> fix: waiting for redirect frequency tweaked

- CHANGELOG.rst
- helm-chart/renku/Chart.yaml
> Updates for 0.7.13

- CHANGELOG.rst
- helm-chart/renku/Chart.yaml
- helm-chart/values.yaml.changelog.md
Add instructions for upgrading from `0.7.12`
No need to deploy or test.
> Update notes for 0.7.13

- helm-chart/renku/values.yaml
Includes changes from SwissDataScienceCenter/contributed-project-templates#4
/deploy
> chore: bump contributed templates reference

- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/DatasetsSearch.scala
Temporary until this https://github.com/SwissDataScienceCenter/renku-ui/issues/1352 is addressed.
/deploy
> tests: increase dataset loading time

- docs/admin/homepage.rst
- docs/admin/index.rst
- helm-chart/renku/values.yaml
- helm-chart/values.yaml.changelog.md
Changes to the `values.yaml` file and documentation to support homepage customization. 
Do not merge until https://github.com/SwissDataScienceCenter/renku-ui/pull/1274 is merged to master.
> docs: describe RenkuLab homepage customization

- acceptance-tests/build.sbt
- acceptance-tests/project/build.properties
> chore: acceptance tests libs upgrade

- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/DatasetPage.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/DatasetsPage.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/ProjectPage.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/TopBar.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/AcceptanceSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/Grammar.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/Datasets.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/Environments.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/Login.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/Project.scala
/deploy renku-ui=ui-design-2021
> fix tests for ui design pr 1274

- acceptance-tests/README.md
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/ProjectPage.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/Environments.scala
Changes required by SwissDataScienceCenter/renku-ui#1344
/deploy renku-ui=1220-session-iframe
> test: update acceptance tests to support session iframe

- CHANGELOG.rst
- helm-chart/renku/Chart.yaml
> Updates for 0.8.1

- helm-chart/renku/values.yaml
Include new templates version.
/deploy
> chore: update templates

- acceptance-tests/src/test/scala/ch/renku/acceptancetests/AnonymousEnvironmentSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/MergeRequestsAndIssuesSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/UnprivilegedEnvironmentSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/ProjectPage.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/AnonEnv.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/Environments.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/JupyterNotebook.scala
/deploy renku-ui=1169-rename-sessions
> test: update tests to support sessions

- docs/user/interactive-running-locally.rst
- Add instructions for using image from private project (fix: #2051)
- Refine documentation
> docs: running renkulab interactive sessions locally

- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/LoginPage.scala
- actions/deploy-renku/Dockerfile
- helm-chart/renku/values.yaml
- scripts/init-realm/init-realm.py
> Configure the Renku realm to use the Renku keycloak theme

- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/LoginPage.scala
> fix: css for the Login button on the provider page

- acceptance-tests/src/test/scala/ch/renku/acceptancetests/HandsOnSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/LoginPage.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/ProjectPage.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/TopBar.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/Environments.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/Login.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/Project.scala
Adapt tests for https://github.com/SwissDataScienceCenter/renku-ui/pull/1385
> Minimal header tests

- helm-chart/renku/values.yaml
> build: activate 1.0.0-beta2 as UI canary

- acceptance-tests/Dockerfile
> chore: updated sbt installation script for AT

- helm-chart/renku/values.yaml
> build: activate 1.0.0-beta3 as UI canary

- CHANGELOG.rst
- helm-chart/renku/Chart.yaml
> Prepare 0.8.3 bugfix release

- helm-chart/renku/requirements.yaml
- helm-chart/renku/values.yaml
> build: activate UI 0.11.14 with 1.0.0-beta4 as UI canary

- .github/workflows/pull-request-test.yml
- actions/deploy-renku/entrypoint.sh
> Parametrize rancher api endpoint

- actions/deploy-renku/entrypoint.sh
> Fix entrypoint typo

- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/DatasetsPage.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/RestClient.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/DatasetsSearch.scala
> fix: flaky FreeTextDatasetSearchSpec

- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/RestClient.scala
> fix: retry when EOF occurs on the Rest Client

- CHANGELOG.rst
No code changes and no content changes in the changelog. I messed up the syntax for the rst file so the formatting in the changelog after it is rendered was ugly.
> chore: fix changelog rst formatting

- helm-chart/renku/values.yaml
> build: activate 1.0.0-beta5 as UI canary

- acceptance-tests/src/test/scala/ch/renku/acceptancetests/HandsOnSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/LineageSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/ProjectPage.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/KnowledgeGraphApi.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/RestClient.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/console/package.scala
> test: lineage spec

- CHANGELOG.rst
- docs/spelling_wordlist.txt
- helm-chart/renku/Chart.yaml
- helm-chart/renku/requirements.yaml
> Updates for 0.8.7

- helm-chart/gitlab/templates/registry-ingress.yaml
- helm-chart/renku-logging/templates/ingress.yaml
- helm-chart/renku/templates/ingress.yaml
AKA "the third time is the charm"...
Tested deploying the chart and also upgrading this chart starting from the latest version
/deploy
> (chore) fix the pathType in the ingress paramters to Prefix

- helm-chart/renku/templates/ingress.yaml
Adding an ingress annotation needed for the UI.
Verified with `helm template` that the generated Ingress includes the correct annotation.
/deploy
> feat: add configuration snippet for ingress

- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/NewProjectPage.scala
This should fix the acceptance tests after https://github.com/SwissDataScienceCenter/renku-project-template/pull/127
/deploy
> chore: fix project creation in tests after description removal

- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/RestClient.scala
> fix: rest client closing too early with a premature EOF

- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/GitLabApi.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/KnowledgeGraphApi.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/RenkuApi.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/RestClient.scala
> fix: premature EOF in acceptance tests

- docs/user/templates.rst
> chore(docs): update list of options to include disk_request

- helm-chart/renku/requirements.yaml
- helm-chart/renku/values.yaml
Changes to support having the UI version 1.0.0 as the default.
/deploy
> Prepare for UI 1.0.0 as default

- acceptance-tests/README.md
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/AnonymousEnvironmentSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/HandsOnSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/MergeRequestsAndIssuesSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/UnprivilegedEnvironmentSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/DatasetPage.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/DatasetsPage.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/LoginPage.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/ProjectPage.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/ProjectsPage.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/TopBar.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/AcceptanceSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/AnonEnv.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/Grammar.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/Collaboration.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/Datasets.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/Environments.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/JupyterNotebook.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/Login.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/Project.scala
- docs/admin/homepage.rst
- docs/admin/index.rst
- docs/spelling_wordlist.txt
- helm-chart/renku/requirements.yaml
- helm-chart/renku/values.yaml
- helm-chart/values.yaml.changelog.md
Changes that go with the new UI design.
/deploy
> Changes for UI 1.0.0

- CHANGELOG.rst
- helm-chart/renku/Chart.yaml
Update documentation/chart on master branch, post `0.9.1` release
> Post 0.9.1 updates

- CHANGELOG.rst
- docs/spelling_wordlist.txt
- helm-chart/renku/Chart.yaml
- helm-chart/renku/requirements.yaml
Updates for `0.10.0`
(deploying since it includes a bump of the ui dependency)
/deploy
> Updates for 0.10.0 release

- CHANGELOG.rst
- helm-chart/renku/Chart.yaml
> Updates for 0.10.2

- chartpress.yaml
> chore: fix chart building

- acceptance-tests/Dockerfile
- chartpress.yaml
> refactor: clean up acceptance test docker file

- docs/topic-guides/teaching_with_renkulab.rst
Use one form instead of two (Google/MS).
> Update with JotForm instead of Google or MS

- CONTRIBUTING.rst
Fix links in contributor doc
closes #2347
> chore: update contributing doc

- helm-chart/renku/requirements.yaml
> chore: updating renku-ui and renku-ui-server version to 1.2.0

- CHANGELOG.rst
- helm-chart/renku/Chart.yaml
Not deploying since all dependencies have been already deployed and tested before merging to master.
> (chore) Prepare 0.10.3 release

- acceptance-tests/src/test/scala/ch/renku/acceptancetests/model/commons.scala
> fix: matching length of CLI version read from console and config

- helm-chart/renku/templates/tests/test-renku.yaml
- helm-chart/renku/values.yaml
> chore(chart): template helm test resource requests/limits

- CHANGELOG.rst
- helm-chart/README.rst
- helm-chart/renku/Chart.yaml
- helm-chart/renku/values.yaml
Testing a CI deployment to run acceptance tests with the newer version of PostgreSQL and current dev's GitLab.
/deploy
> (chore) Prep Renku 0.11.0

- acceptance-tests/project/build.properties
This fixes security issue in Log4j
/deploy
> fix: log4j security issue

- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/ProjectPage.scala
> tests: relax constrain on start button

- helm-chart/README.rst
Fix formatting for a nicer display of GitLab upgrade notes.
> fix: upgrade GitLab notes format

- CHANGELOG.rst
Prepare 0.11.1 release featuring updates to the renku UI.
> chore: changelog for 0.11.1

- helm-chart/renku/values.yaml
Use updated Keycloak theme
/deploy
> chore: make Keycloak theme compatible with current Keycloak version

- .github/workflows/pull-request-test.yml
Do not fail the tests step if no deploy or no tests are requested.
> fix: do not fail tests without deploy

- helm-chart/renku/values.yaml
Incorporate https://github.com/SwissDataScienceCenter/keycloak-theme/pull/11
/deploy
> chore: improve display of error messages in Keycloak theme

- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/DatasetPage.scala
> test: fixing free text search acceptance test

- CHANGELOG.rst
> chore: prep 0.11.3 release

- helm-chart/renku/values.yaml
> build: add uiserver.sentry to values

- .github/workflows/publish-helm-chart.yml
- .github/workflows/publish-master-merges.yaml
- .github/workflows/pull-request-test.yml
> chore: create ci ns outside of rancher projects

- .github/workflows/publish-master-merges.yaml
This should fix the previous mess I made.
> fix(ci): properly set helm chart version

- Pipfile
- Pipfile.lock
ipython should not really be a dev dependency.
> chore: remove ipython as dev dependency

- scripts/install-helm.sh
Looks like some unused leftover from early days.
> chore: remove unused script

- CHANGELOG.rst
> chore: prepare release 0.12.2

- CHANGELOG.rst
> chore: add info about broken core metrics

- .github/workflows/publish-helm-chart.yml
It looks we've got some variables' names mismatched.
> chore: docker credentials updated in publish-helm-chart.yml

- .github/workflows/publish-master-merges.yaml
> chore(ci): use org secrets everywhere

- helm-chart/renku/requirements.yaml
Just for testing - ignore.
NOT merging into master.
> IGNORE: just for testing

- CHANGELOG.rst
- helm-chart/renku/requirements.yaml
> chore: prepare release 0.12.3

- helm-chart/renku/values.yaml
As it says on the tin. 
/deploy
> chore: bump project template version

- CHANGELOG.rst
- helm-chart/renku/Chart.yaml
> chore: prep 0.12.4

- CHANGELOG.rst
- helm-chart/renku/Chart.yaml
> chore: release 0.12.5

- docs/requirements.txt
updates the renku-python submodule reference.
> chore: update renku-python for docs

- docs/how-to-guides/index.rst
- docs/how-to-guides/s3.rst
- docs/how-to-guides/sessions.rst
Adds a how-to-article on mounting s3 buckets.
> chore(docs): add how to guide for s3 buckets

- .github/workflows/pull-request-test.yml
> chore: use concurrency in actions

- docs/tutorials/first_steps/03_add_data.rst
> fix(docs): corrects broken link

- helm-chart/certificates/templates/_volume-mounts.tpl
chore: update java 18 cert
related to https://github.com/SwissDataScienceCenter/renku-graph/issues/836
> chore: Update java 18 cert

- CHANGELOG.rst
- helm-chart/renku/Chart.yaml
> chore: prep release 0.12.7

- CHANGELOG.rst
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/RenkuApi.scala
- helm-chart/renku/requirements.yaml
Release with various bug fixes on Renku components.
/deploy
> chore: prep release 0.12.9

- CHANGELOG.rst
- docs/conf.py
- docs/reference/index.rst
- helm-chart/renku/values.yaml
Release notes for 0.12.10 and update to templates.
> chore: prep 0.12.10

- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/DatasetPage.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/NewProjectPage.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/TopBar.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/DatasetsSearch.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/Project.scala
- helm-chart/renku/requirements.yaml
Fixes for tests for the next version of Renku (2.0-next)
> Fixes for tests for the next version of Renku (2.0-next)

- acceptance-tests/Dockerfile
- acceptance-tests/build.sbt
- acceptance-tests/project/build.properties
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/AnonymousEnvironmentSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/UnprivilegedEnvironmentSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/model/projects.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/JupyterLabPage.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/Page.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/ProjectPage.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/AnonEnv.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/GitLabApi.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/Grammar.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/WebDriverOps.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/Environments.scala
It was observed that the Unprivileged Session spec fails intermittently. This PR tries to fix that.
/deploy
> test: unpriviledged spec intermittent failures

- acceptance-tests/src/test/scala/ch/renku/acceptancetests/AnonymouSessionSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/HandsOnSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/UnprivilegedSessionSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/ProjectPage.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/Grammar.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/Environments.scala
> fix: flaky UnprivilegedEnvironmentSpec

- acceptance-tests/src/test/scala/ch/renku/acceptancetests/LineageSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/model/projects.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/NewProjectPage.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/ProjectPage.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/Grammar.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/Datasets.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/Environments.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/Project.scala
> fix: flaky unprivileged session test

- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/Grammar.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/Environments.scala
> fix: intermittent failures for unprivileged session spec

- CHANGELOG.rst
- docs/spelling_wordlist.txt
add blurb about renku-notebooks values change.
> update renku-notebooks changelog

- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/DatasetsPage.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/Page.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/RenkuPageCommons.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/Grammar.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/Environments.scala
> fix: tests around session starting made more robust

- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/ProjectPage.scala
This should fix the acceptance tests for deployments where anonymous sessions are disabled.
/deploy
> test: fix anon disabled

- CHANGELOG.rst
Some guidelines for filling in:
* be specific: avoid making general sentences such as 'improvements to x'.
* think as a user: avoid using back-end terms, starting from the components name. For instance use words like: authentication, user session, file display, datasets (these could be used for both UI and Core). Also, avoid giving details of how the issue or improvement was implemented.
> prep: release 0.12.13

- CHANGELOG.rst
- helm-chart/renku/Chart.yaml
Prep next renku release. Notes to be filled in by @ciyer and @olevski .
> Prep 0.12.17

- docs/conf.py
Updates dates and authors in the docs.
> chore: update dates and authors

- helm-chart/renku/templates/_keycloak-clients-users.tpl
> fix(chart): set device auth polling interval to 5 seconds

- helm-chart/certificates/Chart.yaml
- helm-chart/renku/requirements.yaml
- helm-chart/renku/values.yaml
Manual release of the new certificates helm chart and update of the associated values.
> chore: certificates 0.0.3 release

- CHANGELOG.rst
- docs/spelling_wordlist.txt
- helm-chart/renku/Chart.yaml
To be completed with component updates.
> chore: prep 0.13.0

- CHANGELOG.rst
> chore: prepare release 0.15.0

- helm-chart/renku/values.yaml
> chore: bump renkulab template version

- CHANGELOG.rst
- helm-chart/values.yaml.changelog.md
> chore: prepare release 0.16.0

- helm-chart/renku/Chart.yaml
Newer versions of Renku have been made but the chart was not updated, this PR fixes this.
> fix: update chart version

- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/JupyterLabPage.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/ProjectPage.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/TopBar.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/Collaboration.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/Datasets.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/Environments.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/JupyterNotebook.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/Project.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/Settings.scala
Changes to the tests for the new UI version.
> Acceptance tests for UI 2.8.0

- .github/workflows/pull-request-test.yml
- CHANGELOG.rst
- helm-chart/renku/requirements.yaml
> chore: prepare 0.17.0

- helm-chart/renku/Chart.yaml
This PR aligns value in the Chart.yaml with the renku release.
> chore: fixing chart version

- acceptance-tests/src/test/scala/ch/renku/acceptancetests/HandsOnSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/DatasetPage.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/DatasetsPage.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/ProjectPage.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/WelcomePage.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/Datasets.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/Environments.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/Project.scala
rel https://github.com/SwissDataScienceCenter/renku-ui/pull/1978
Note: will only merge when  https://github.com/SwissDataScienceCenter/renku-ui/pull/1994 is ready to be merged 😉
> fix: modify css selector in acceptance tests after apply design styles 

- CHANGELOG.rst
Added missing content to change log.
> chore: complete 0.17.1 changelog

- helm-chart/values.yaml.changelog.md
* chore: documenting changes to renku-ui helm chart
> Changes for renku-ui 2.9.0

- CHANGELOG.rst
- helm-chart/renku/requirements.yaml
- helm-chart/values.yaml.changelog.md
* documenting changes to renku-ui helm chart
* update changelog
> chore: updating renku-ui version to 2.9.0

- CHANGELOG.rst
- helm-chart/renku/Chart.yaml
Updates to changlog for 0.18.0
> Release 0.18.0

- CHANGELOG.rst
> chore: prep 0.18.3 release

- acceptance-tests/README.md
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/DatasetUploadSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/HandsOnSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/MergeRequestsAndIssuesSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/DatasetPage.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/GitLabUserProfilePage.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/GitLabWelcomePage.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/ProjectPage.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/TopBar.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/Grammar.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/Collaboration.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/Datasets.scala
- acceptance-tests/tests-defaults.conf.template
This PR improves tests stability around the dataset and analysis results verification.
> test: improving tests reliability

- CHANGELOG.rst
Preparation for release 0.19.0
/deploy
> chore: prepare release 0.19.0

- helm-chart/gitlab/Chart.yaml
- helm-chart/gitlab/requirements.yaml
- helm-chart/gitlab/templates/_gitlab.rb.tpl
- helm-chart/gitlab/templates/deployment.yaml
- helm-chart/gitlab/values.yaml
> chore(gitlab): remove redis from gitlab chart

- helm-chart/renku/values.yaml
Update key cloak theme to unify appearance with the RenkuLab UI.
> build: update keycloak theme

- CHANGELOG.rst
> Changelog for 0.20.0

- cypress-tests/.eslintignore
- cypress-tests/.eslintrc.json
- cypress-tests/.gitignore
- cypress-tests/README.md
- cypress-tests/config.ts
- cypress-tests/cypress.config.ts
- cypress-tests/cypress.env.template.json
- cypress-tests/cypress/e2e/rstudioSession.cy.ts
- cypress-tests/cypress/support/commands/general.ts
- cypress-tests/cypress/support/commands/login.ts
- cypress-tests/cypress/support/commands/projects.ts
- cypress-tests/cypress/support/commands/sessions.ts
- cypress-tests/cypress/support/e2e.ts
- cypress-tests/cypress/support/index.ts
- cypress-tests/package-lock.json
- cypress-tests/package.json
A PR with refactoring that do preparatory work before developing new tests.
* Upgrade cypress
* Add team-standard style and lint configurations and reformat code in accordance
* Introduce some standard scripts (`e2e` to run cypress in e2e mode, `lint` to run the linter)
* Restructure code to follow Cypress best-practice guidelines https://docs.cypress.io/guides/references/best-practices
> Cypress tests refactor

- default.nix
- docs/how-to-guides/contributing/documentation.rst
- docs/spelling_wordlist.txt
This PR adds a nix configuration that simplifies dependency management for building charts and documentation from the main renku repository.
> chore: add nix configuration

- .github/workflows/pull-request-test.yml
- cypress-tests/README.md
- cypress-tests/cypress/e2e/publicProject.cy.ts
- cypress-tests/cypress/support/commands/general.ts
- cypress-tests/cypress/support/commands/projects.ts
Covers most of #2797, except changing the session settings with will be handled in https://github.com/SwissDataScienceCenter/renku-ui/issues/2215
/deploy #persist #notest #cypress
> Additional cypress-based tests for the UI

- acceptance-tests/requirements.txt
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/FlightsTutorial.scala
> chore: minimal requirements.txt for acceptance tests

- acceptance-tests/Dockerfile
> chore: tests docker image to extend python:3.9

- CHANGELOG.rst
> Update changelog for 0.21.0

- cypress-tests/cypress.config.ts
- cypress-tests/cypress/e2e/publicProject.cy.ts
- cypress-tests/cypress/support/commands/projects.ts
/deploy #persist #cypress #notest renku-ui=master
> Renku UI 2.15.0 test improvements

- cypress-tests/cypress/e2e/publicProject.cy.ts
- cypress-tests/package-lock.json
- cypress-tests/package.json
Improve Cypress acceptance tests ("project" section) by making the tests more resilient to UI elements refreshing
/deploy #persist #notest #cypress
> test(cypress): improve resilience to refreshing components

- cypress-tests/cypress/e2e/publicProject.cy.ts
- cypress-tests/cypress/support/commands/general.ts
This PR is only to stabilize existing tests, a pre-requisite to #2853 
/deploy #notest #persist #cypress renku-ui=master
> test(cypress): wait for resources to be loaded/available

- cypress-tests/cypress/e2e/publicProject.cy.ts
- cypress-tests/cypress/support/commands/general.ts
PR to modify selector for project search in new cross entity search.
/deploy renku-ui=master #persist #cypress
> test: update cypress test for new projects search

- cypress-tests/config.ts
- cypress-tests/cypress/e2e/publicProject.cy.ts
- cypress-tests/cypress/e2e/updateProjects.cy.ts
- cypress-tests/cypress/support/commands/general.ts
- cypress-tests/cypress/support/commands/projects.ts
Add tests to:
- Fork a project.
- Update a project from the previous version and verify the commits are pushed correctly.
- Assess we can't update very old projects.
This includes a few optimizations to the public project tests to improve stability.
/deploy #notest #cypress #persist
fix #2853
> test(cypress): add tests for forking and updating projects

- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/ProjectPage.scala
- cypress-tests/cypress/e2e/publicProject.cy.ts
- cypress-tests/cypress/e2e/rstudioSession.cy.ts
- cypress-tests/cypress/e2e/updateProjects.cy.ts
- cypress-tests/cypress/support/commands/login.ts
- cypress-tests/cypress/support/commands/sessions.ts
> Tmp20230125

- acceptance-tests/Dockerfile
- acceptance-tests/requirements.txt
- helm-chart/renku/values.yaml
> chore: bump template version

- CHANGELOG.rst
> chore: prepare release 0.23.0

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yaml
- .github/ISSUE_TEMPLATE/documentation.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/workflows/github-project.yml
Updates the issue template to add Triage labels and emojis.
Also adds links to discourse and gitter on the "New issue" page.
Adds new template for documentation issues.
Changes labels for bug, enhancement to kind/bug and kind/enhancement
> update issue templates with triage labels and discussion links

- .github/workflows/check-acceptance-test-code.yml
- .github/workflows/check-acceptance-test-fmt.yml
- .github/workflows/pull-request-test.yml
Adds triggers for actions to run on merge group PRs.
> chore: add merge group action triggers

- .github/dependabot.yml
Adds configuration to automatically update github actions.
> chore: update actions with dependabot

- CHANGELOG.rst
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/WelcomePage.scala
- cypress-tests/cypress/e2e/rstudioSession.cy.ts
- cypress-tests/cypress/support/commands/sessions.ts
PR to update acceptance tests and cypress test for dashboard.
/deploy #persist renku-ui=2286-dashboard
> test: UI dashboard

- CHANGELOG.rst
- cypress-tests/cypress/e2e/publicProject.cy.ts
- cypress-tests/cypress/e2e/rstudioSession.cy.ts
- cypress-tests/cypress/e2e/updateProjects.cy.ts
- cypress-tests/cypress/support/commands/projects.ts
- helm-chart/renku/requirements.yaml
Renku UI version 3.3.0
/deploy #persist renku-notebooks=master
> Renku UI 3.3.0

- helm-chart/renku/values.yaml
update values to disable ssh by default
> chore: update values with better SSH support values

- acceptance-tests/build.sbt
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/AcceptanceSpec.scala
Apparently, since Chrome 111 Selenium has a bit of difficulty connecting to the browser (see [here for more](https://github.com/SeleniumHQ/selenium/issues/11750)). This PR follows the suggestion mentioned in the ticket.
> fix: selenium cannot connect to chrome

- .github/CODEOWNERS
> Make Product Mgmt the sole owner of the CHANGELOG

- CHANGELOG.rst
This PR contains changelog refinements for 0.24.2
> chore: changelog refinements for 0.24.2

- cypress-tests/cypress/e2e/publicProject.cy.ts
- cypress-tests/cypress/support/commands/projects.ts
* update waits to match new request structure
/deploy #persist #notest #cypress renku-ui=master
> Update tests for UI 3.4.0

- CHANGELOG.rst
- cypress-tests/cypress/e2e/publicProject.cy.ts
- cypress-tests/cypress/support/commands/projects.ts
- helm-chart/renku/requirements.yaml
This contains the same changes from #3010
> build: update renku-ui version to 3.4.0

- chartpress.yaml
- helm-chart/renku/Chart.yaml
- helm-chart/renku/requirements.yaml
- helm-chart/renku/templates/NOTES.txt
- helm-chart/renku/templates/_helpers.tpl
- helm-chart/renku/templates/_keycloak-clients-users.tpl
- helm-chart/renku/templates/configmap.yaml
- helm-chart/renku/templates/ingress.yaml
- helm-chart/renku/templates/keycloak-password-secret.yaml
- helm-chart/renku/templates/keycloak-postgres-secret.yaml
- helm-chart/renku/templates/network-policies.yaml
- helm-chart/renku/templates/post-install-job-keycloak.yaml
- helm-chart/renku/templates/secrets.yaml
- helm-chart/renku/values.yaml
Reverts SwissDataScienceCenter/renku#2904
There are **at least** 2 problems:
1. the buttons for other login methods are in the wrong place
2. something broke with the OAuth2 GH auth
> Revert "chore: upgrade from keycloak to keycloakx chart"

- helm-chart/renku/values.yaml
Bumps the project templates tag.
> chore: update project template ref

- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/DatasetPage.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/GraphStatus.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/GraphStatusSpec.scala
- cypress-tests/cypress/e2e/publicProject.cy.ts
- cypress-tests/cypress/e2e/updateProjects.cy.ts
- cypress-tests/cypress/e2e/useSession.cy.ts
- cypress-tests/cypress/e2e/verifyInfrastructure.cy.ts
- cypress-tests/cypress/support/commands/general.ts
- cypress-tests/cypress/support/commands/login.ts
- cypress-tests/cypress/support/commands/projects.ts
Attempt to fix acceptance tests
> Update acceptance tests

- docs/how-to-guides/own_machine/cli-installation.rst
- docs/reference/templates.rst
Documents for renaming templates in https://github.com/SwissDataScienceCenter/renku-python/pull/3347.
> chore: docs for renaming templates

- docs/requirements.txt
> chore(deps): bump renku-sphinx-theme from 0.2.2 to 0.2.3 in /docs

- CHANGELOG.rst
- helm-chart/renku/requirements.yaml
Update renku UI to version 3.4.3
> Update renku UI 3.4.3

- cypress-tests/cypress/e2e/rstudioSession.cy.ts
- cypress-tests/cypress/e2e/useSession.cy.ts
- cypress-tests/cypress/support/commands/projects.ts
- cypress-tests/cypress/support/commands/sessions.ts
Close all running sessions in `useSession.cy.ts` before running the tests. This should fix zombie sessions making tests fail.
Fixes #3009.
/deploy #persist #cypress
> fix(cypress): close all existing running sessions in useSession

- CHANGELOG.rst
- helm-chart/renku/requirements.yaml
> Update from auto-update/renku-graph-2.33.0

- .github/workflows/auto-reqs-update-pr.yml
the code to set the PR body used a reference for sharing output between jobs instead of between steps
> chore: fix pr body in auto-pr action

- docs/how-to-guides/own_machine/index.rst
- docs/how-to-guides/own_machine/session-running-locally.rst
- docs/how-to-guides/own_machine/session-running-remotely.rst
closes https://github.com/SwissDataScienceCenter/renku-python/issues/3229
> docs: add docs for running renku sessions on a remote machine

- acceptance-tests/src/test/scala/ch/renku/acceptancetests/HandsOnSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/LineageSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/model/projects.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/ProjectPage.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/Settings.scala
- cypress-tests/cypress/e2e/publicProject.cy.ts
See: https://github.com/SwissDataScienceCenter/renku-ui/pull/2495
/deploy #persist renku-ui=master
> tests: update acceptance tests for renku-ui >3.4.3

- CHANGELOG.rst
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/HandsOnSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/LineageSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/model/projects.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/ProjectPage.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/Settings.scala
- cypress-tests/cypress/e2e/publicProject.cy.ts
- helm-chart/renku/requirements.yaml
This includes Changelogs and the necessary changes to the acceptance tests
> Update UI to version 3.5.0

- scripts/init-realm/init-realm.py
description to make action happy
> fix(post-install-keycloak): catch the correct exception since lib update.

- CHANGELOG.rst
- chartpress.yaml
- docs/spelling_wordlist.txt
- helm-chart/renku/Chart.yaml
- helm-chart/renku/requirements.yaml
- helm-chart/renku/templates/NOTES.txt
- helm-chart/renku/templates/_helpers.tpl
- helm-chart/renku/templates/_keycloak-clients-users.tpl
- helm-chart/renku/templates/configmap.yaml
- helm-chart/renku/templates/ingress.yaml
- helm-chart/renku/templates/keycloak-password-secret.yaml
- helm-chart/renku/templates/keycloak-postgres-secret.yaml
- helm-chart/renku/templates/network-policies.yaml
- helm-chart/renku/templates/post-install-job-keycloak.yaml
- helm-chart/renku/templates/secrets.yaml
- helm-chart/renku/values.yaml
- helm-chart/values.yaml.changelog.md
> chore: upgrade Keycloak

- helm-chart/renku/templates/configmap.yaml
The database is now created with the service user as the owner.
/deploy
> chore: Create triples-generator db owned by the service user

- cypress-tests/cypress/e2e/verifyInfrastructure.cy.ts
> test(cypress): update the renku-core version endpoint URL

- .github/workflows/pull-request-test.yml
- CHANGELOG.rst
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/FreeTextDatasetSearchSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/DatasetsPage.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/Datasets.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/DatasetsSearch.scala
- cypress-tests/cypress.config.ts
- cypress-tests/cypress/e2e/publicProject.cy.ts
- helm-chart/renku/requirements.yaml
Update renku UI to version 3.10.0
> Update from auto-update/renku-ui-3.10.0

- helm-chart/renku/templates/renku-version-configmap.yaml
In support of https://github.com/SwissDataScienceCenter/renku-ui/issues/2664
> Chart changes for showing renku version in UI

- CHANGELOG.rst
Modified description of the changelog and formatting issues.
> chore: Update CHANGELOG.rst

- cypress-tests/cypress/e2e/publicProject.cy.ts
Use "indexing" instead of "processing"
> tests: update tests for renaming of KG to 'Metadata indexing'

- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/DatasetPage.scala
- cypress-tests/cypress/e2e/publicProject.cy.ts
* update tests for renaming of KG to 'Metadata processing'
> Updates to acceptance tests for UI 3.11

- CHANGELOG.rst
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/DatasetPage.scala
- cypress-tests/cypress/e2e/publicProject.cy.ts
- helm-chart/renku/requirements.yaml
Update UI to version 3.11.0 and adjust the tests where needed.
> Update from auto-update/renku-ui-3.11.0

- CHANGELOG.rst
- helm-chart/renku/values.yaml
Added to bug fix release 0.35.1.
> chore: update CRC service to 0.0.2

- CHANGELOG.rst
- helm-chart/renku/requirements.yaml
Update the UI to version 3.12.1.
> chore: bump UI to version 3.12.1

- cypress-tests/cypress/e2e/rstudioSession.cy.ts
- cypress-tests/cypress/e2e/useSession.cy.ts
- cypress-tests/cypress/support/commands/sessions.ts
- load-tests/scenarioLecture.js
Updates Cypress tests and function for tests
re SwissDataScienceCenter/renku-ui/issues/2686
/deploy renku-ui=master renku-notebooks=1.19.0 extra-values=notebooks.userSessionPersistentVolumes.enabled=true
> test(cypress): update session tests and functions

- cypress-tests/cypress/e2e/testDatasets.cy.ts
This should fix the dataset tests.
/deploy
> test(cypress): fix editing dataset

- CHANGELOG.rst
- helm-chart/renku/templates/gateway/_helpers.tpl
- helm-chart/renku/templates/gateway/deployment-revproxy.yaml
- helm-chart/renku/templates/gateway/deployment.yaml
- helm-chart/renku/templates/gateway/service.yaml
- helm-chart/renku/values.yaml
See the changelog for details.
> fix(chart): do not change immutable gateway deployment selector labels

- helm-chart/renku/templates/ui/ui-client-deployment-template.yaml
- helm-chart/renku/templates/ui/ui-server-deployment.yaml
Fixes https://github.com/SwissDataScienceCenter/renku-ui/issues/2836.
/deploy
> fix(ui): fix UI versions

- cypress-tests/cypress/e2e/useSession.cy.ts
Note: tested against https://renku-ci-ui-2760.dev.renku.ch/
Note: merging into #3214.
> tests: add cypress test to validate cloud storage

- CHANGELOG.rst
> chore: update release notes for 0.40.2

- CHANGELOG.rst
- cypress-tests/cypress/e2e/useSession.cy.ts
- helm-chart/renku/templates/_helpers.tpl
- helm-chart/renku/templates/gateway/deployment-revproxy.yaml
- helm-chart/renku/templates/gateway/deployment.yaml
- helm-chart/renku/templates/notebooks/statefulset.yaml
- helm-chart/renku/templates/notebooks/test.yaml
- helm-chart/renku/templates/ui/ui-client-deployment-template.yaml
- helm-chart/renku/templates/ui/ui-server-deployment.yaml
- helm-chart/renku/values.yaml
/deploy extra-values=global.gitlab.url=https://gitlab.dev.renku.ch,notebooks.cloudstorage.s3.enabled=true,amalthea.extraChildResources[0].group=com.ie.ibm.hpsys,amalthea.extraChildResources[0].name=datasets,notebooks.cloudstorage.s3.installDatashim=false
> feat: admin panel for compute resources

- CHANGELOG.rst
> chore: update changelog for #3313

- helm-chart/renku/values.yaml
This PR reduces the size of the connection pool on TG to 5.
> chore: reduced connection pool size for TG to 5

- CHANGELOG.rst
- helm-chart/renku/values.yaml
Bring bugfix changes to main branch. 
/deploy
> chore: merge 0.42.x

- CHANGELOG.rst
- helm-chart/renku/values.yaml
> chore: update renku-data-services to 0.2.3

- CHANGELOG.rst
Formatting and wordsmithing in the changelog...
> Update CHANGELOG.rst for 0.44.0

- CHANGELOG.rst
Fine tuning user facing section.
> Update Changelog for 0.45.0

- helm-chart/renku/templates/data-service/deployment.yaml
Fixes https://github.com/SwissDataScienceCenter/renku-data-services/issues/108.
URL for test: https://ci-renku-3398.dev.renku.ch/ui-server/api/data/version
/deploy
> chore: propagate the data-services image tag

- CHANGELOG.rst
- helm-chart/renku/templates/notebooks/role.yaml
- helm-chart/renku/values.yaml
These component updates will fix the problems with the expiring Gitlab tokens.
> fix: new gateway and notebooks releasese for expiring Gitlab tokens

- cypress-tests/cypress/e2e/useSession.cy.ts
Update cypress tests for the new Cloud Storage options.
> test(cypress): update cloud storage test

- CHANGELOG.rst
- helm-chart/renku/values.yaml
> Update from auto-update/renku-graph-2.49.0

- CHANGELOG.rst
- event.json
Also, remove `event.json`.
Before:
After:
> fix: fix the changelog

- CHANGELOG.rst
> chore: update changelog

- .github/workflows/renku-dev-test.yaml
- CHANGELOG.rst
- helm-chart/renku/values.yaml
* Bump UI version to 3.20.0
* Add dependency update for running Cypress through actions
/deploy
> bump UI version to 3.20.0

- docs/how-to-guides/admin/privacycookie.rst
- helm-chart/renku/templates/NOTES.txt
- helm-chart/renku/templates/ui/ui-client-configmap.yaml
- helm-chart/renku/templates/ui/ui-client-deployment-template.yaml
- helm-chart/renku/values.yaml
- helm-chart/values.yaml.changelog.md
Related to https://github.com/SwissDataScienceCenter/renku-ui/issues/2954
/deploy #persist renku-ui=main extra-values=ui.client.privacy.page.enabled=true
> feat: make configuration of privacy policy more flexible

- CHANGELOG.rst
- docs/how-to-guides/admin/privacycookie.rst
- helm-chart/renku/templates/ui/ui-client-configmap.yaml
- helm-chart/renku/templates/ui/ui-client-deployment-template.yaml
- helm-chart/renku/values.yaml
- helm-chart/values.yaml.changelog.md
/deploy #notest extra-values=ui.client.privacy.page.enabled=true,ui.client.privacy.page.privacyPolicyContent=Test
> fix: change the privacy configmap behavior

- acceptance-tests/build.sbt
This PR upgrades Logback on selenium tests
> chore: logback update to 1.5.0

- .github/workflows/publish-helm-chart.yml
- CHANGELOG.rst
- docs/how-to-guides/admin/privacycookie.rst
- helm-chart/renku/templates/ui/ui-client-configmap.yaml
- helm-chart/renku/templates/ui/ui-client-deployment-template.yaml
- helm-chart/renku/values.yaml
- helm-chart/values.yaml.changelog.md
This merges back to `master` the commits added for the release `0.48.1` from the branch [0.48.x](https://github.com/SwissDataScienceCenter/renku/commits/release-0.48.x)
/deploy
> Merge commits from bugfix release 0.48.1

- .github/workflows/release-test.yml
> chore: add check for open prs on release branches

- acceptance-tests/build.sbt
- acceptance-tests/project/build.properties
* sbt to 1.9.9
* pureconfig to 0.17.6
> chore: selenium tests libs upgrade

- cypress-tests/config.ts
- cypress-tests/cypress/e2e/rstudioSession.cy.ts
- cypress-tests/cypress/e2e/useSession.cy.ts
- cypress-tests/cypress/support/commands/sessions.ts
> fix(cypress): make session actions more robust

- acceptance-tests/build.sbt
This PR updates scala on acceptance-tests
> chore: scala update to 2.13.13

- .github/workflows/renku-dev-test.yaml
- CHANGELOG.rst
- RELEASE.md
- docs/how-to-guides/admin/privacycookie.rst
- helm-chart/renku/requirements.yaml
- helm-chart/renku/templates/NOTES.txt
- helm-chart/renku/templates/setup-job-gitlab.yaml
- helm-chart/renku/templates/setup-job-keycloak-db.yaml
- helm-chart/renku/templates/setup-job-renku-dbs.yaml
- helm-chart/renku/values.yaml
- helm-chart/utils/postgres_migrations/version_upgrades/psql_dump.yaml
- helm-chart/utils/postgres_migrations/version_upgrades/psql_load.yaml
- helm-chart/values.yaml.changelog.md
/deploy
Refreshes #2894 and supercedes it.
> chore(postgres): Upgrade Postgres to version 16.1.0

- CHANGELOG.rst
> Update naming from Renku 1.0 to 2.0

- acceptance-tests/build.sbt
This PR updates:
* cats-effect
* http4s-circe
* slf4j-log4j12
> chore: selenium tests libs upgrades

- CHANGELOG.rst
- helm-chart/renku/values.yaml
Note: the target branch is 0.49.0, there was no 0.49.x
/deploy
> chore: 0.49.1 release

- CHANGELOG.rst
- acceptance-tests/build.sbt
- helm-chart/renku/values.yaml
A new bugfix release. This was already reviewed by everyone needed and merged here: https://github.com/SwissDataScienceCenter/renku/pull/3546
/deploy
> chore: release 0.49.1

- helm-chart/renku/values.yaml
> bump renku-ui, renku-notebooks

- acceptance-tests/requirements.txt
> chore: streamline acceptance test dependencies

- CHANGELOG.rst
Clarified that the Renku 2.0 features are hidden to users. Also cleaned up some long lines.
> 0.50.0 Changelog

- CHANGELOG.rst
- helm-chart/renku/values.yaml
/deploy values=global.gitlab.url=https://gitlab.dev.renku.ch,global.gitlab.registry.host=registry.dev.renku.ch/
> feat: Renku 2.0 namespaces and groups

- helm-chart/values.yaml.changelog.md
This is my attempt to provide some notes on the search and solr components,  addressing #3555
> Add lines about new search and solr components

- CHANGELOG.rst
- cypress-tests/cypress/support/commands/sessions.ts
- helm-chart/renku/values.yaml
Adding the changes from 0.51.1 to 0.52.x branch.
> chore: add changes from 0.51.1 to 0.52.0

- helm-chart/renku/values.yaml
- scripts/platform-init/platform-init.py
/deploy renku-notebooks=master
> fix: add missing value in values.yaml for secrets mount

- CHANGELOG.rst
- helm-chart/renku/values.yaml
> chore: bump renku notebooks to 1.23.0

- CHANGELOG.rst
- docs/spelling_wordlist.txt
- helm-chart/renku/templates/_certificates-env.tpl
- helm-chart/renku/templates/_certificates-init-container.tpl
- helm-chart/renku/templates/_certificates-volumes.tpl
- helm-chart/renku/templates/_helpers.tpl
- helm-chart/renku/templates/authz/deployment.yaml
- helm-chart/renku/templates/data-service/deployment.yaml
- helm-chart/renku/templates/keycloak-users-sync-cronjob.yaml
- helm-chart/renku/templates/secret-renku-internal-tls.yaml
- helm-chart/renku/templates/setup-job-keycloak-realms.yaml
- helm-chart/renku/values.yaml
- scripts/init-realm/init-realm.py
This is the PR that will combine all components and changes for the authorization service and its integration with Renku 2.0 projects.
/deploy
> feat: authorization service and Renku 2.0 project integration

- CHANGELOG.rst
- helm-chart/renku/values.yaml
/deploy renku-ui=build/auth-demo
> Update search services to 0.0.46

- CHANGELOG.rst
- helm-chart/renku/values.yaml
> feat: UI support for User Secrets

- CHANGELOG.rst
- helm-chart/renku/values.yaml
> feat: authorization for Renku 2.0 groups and namespaces

- CHANGELOG.rst
- helm-chart/renku/templates/search/search-api-deployment.yaml
- helm-chart/renku/templates/search/search-provision-deployment.yaml
- helm-chart/renku/values.yaml
> Update search 0.2.0

- RELEASE.md
> Merge master into 0.53.x

- CHANGELOG.rst
- helm-chart/renku/templates/data-service/cronjobs.yaml
- helm-chart/renku/values.yaml
- helm-chart/values.yaml.changelog.md
> release 0.52.1

- CHANGELOG.rst
- helm-chart/renku/values.yaml
> chore: update renku-ui to 3.28.0

- CHANGELOG.rst
- helm-chart/renku/values.yaml
Release 0.52.2
/deploy extra-values=dataService.sentry.enabled=true,dataService.sentry.dsn=https://e47c95d665684bce89984bd4595268df@sentry.dev.renku.ch/13,dataService.sentry.environment=ci-renku-3548,dataService.sentry.sampleRate=0.5
> release 0.52.2

- CHANGELOG.rst
- helm-chart/renku/values.yaml
Updates renku-data-services from v0.14.0 to v.14.1 which brings bug fixes.
/deploy
> fix: update renku-data-services to v0.14.1

- CHANGELOG.rst
- helm-chart/renku/values.yaml
Updates renku-ui from 3.28.0 to 3.28.1 which brings a bug fix.
/deploy
> fix: update renku-ui to 3.28.1

- helm-chart/renku/templates/search/search-api-deployment.yaml
- helm-chart/renku/values.yaml
- helm-chart/values.yaml.changelog.md
> Set default value for jwt.allowedIssuerUrls

- .github/dependabot.yml
combines dependabot updates by ecosystem and groups dependabot PRs
> chore: combine dependabot updates

- cypress-tests/cypress/support/commands/login.ts
Fixes the cypress tests getting stuck at the login step.
/deploy
> fix: get cypress tests to go through the GitLab OAuth screen

- cypress-tests/cypress/e2e/useSession.cy.ts
/deploy renku-ui=ciyer/storage-credentials-prompt renku-notebooks=1.25.2
> test: update useSession test to match UI changes

- scripts/platform-init/platform-init.py
> fix: properly encode generated secret service key

- docs/requirements.txt
See: https://github.com/SwissDataScienceCenter/renku/actions/runs/10037839722/job/27738686275.
^ Docs do not work when using sphinx >= 7.0.
> fix: use sphinx < 7.0

- CHANGELOG.rst
Add release summary statement.
> chore: add release summary

- .github/workflows/pull-request-test.yml
- CHANGELOG.rst
- helm-chart/renku/requirements.yaml
> feat: upgrade Amalthea to 0.12.2

- CHANGELOG.rst
- helm-chart/renku/values.yaml
> bump data services to 0.19.0

- CHANGELOG.rst
- helm-chart/renku/values.yaml
> fix: data service user email validation

- CHANGELOG.rst
- helm-chart/renku/values.yaml
> feat: update search services to 0.5.0

- CHANGELOG.rst
- docs/spelling_wordlist.txt
- helm-chart/renku/values.yaml
Support for saving cloud storage credentials and providing them in the session.
> feat: update notebooks to 1.26.0

- helm-chart/renku/values.yaml
Unfortunately, I forgot to add new configuration values.
/deploy #notest
> fix: fix config for search services

- CHANGELOG.rst
- helm-chart/renku/values.yaml
> feat: update renku-data-services to v0.20.0 and renku-ui to 3.35.0

- CHANGELOG.rst
- helm-chart/renku/values.yaml
Clarifications and wordsmithing
> Polish release 0.57.0 changelog

- CHANGELOG.rst
- cypress-tests/cypress/e2e/useSession.cy.ts
- helm-chart/renku/values.yaml
Fixes the crash loop of `ui-server`.
/deploy
> fix: bump ui to 3.35.1

- CHANGELOG.rst
- helm-chart/renku/requirements.yaml
Addresses these problems: https://github.com/SwissDataScienceCenter/renku-data-services/issues/424
> fix: update csi rclone to 0.3.3

- CHANGELOG.rst
- helm-chart/renku/templates/_helpers.tpl
- helm-chart/renku/templates/search/search-provision-deployment.yaml
- helm-chart/renku/values.yaml
> Update search services to 0.6.1

- CHANGELOG.rst
- helm-chart/renku/templates/notebooks/role.yaml
- helm-chart/renku/values.yaml
Update the gateway and add RBAC for new amalthea.
/deploy
> feat: update gateway and add RBAC for new amalthea

- CHANGELOG.rst
- docs/spelling_wordlist.txt
- helm-chart/renku/values.yaml
> feat: renku v2 dashboard improvements

- CHANGELOG.rst
- cypress-tests/cypress/support/commands/login.ts
- helm-chart/renku/values.yaml
Updates the UI to fix the HTTP 500 upon logging in with gateway 1.1.0.
/deploy
> fix: update renku-ui to 3.37.1

- .github/workflows/check-acceptance-test-code.yml
- .github/workflows/check-acceptance-test-fmt.yml
Port the fix into this patch branch too.
> build: fix scala actions (#3809)

- .github/workflows/check-acceptance-test-code.yml
- .github/workflows/check-acceptance-test-fmt.yml
- .github/workflows/cron-jobs.yaml
- .github/workflows/publish-helm-chart.yml
- .github/workflows/publish-master-merges.yaml
- .github/workflows/pull-request-test.yml
- .github/workflows/renku-dev-test.yaml
- CHANGELOG.rst
- helm-chart/renku/values.yaml
> bump search to 0.6.2

- CHANGELOG.rst
- helm-chart/renku/templates/graph/commit-event-service-deployment.yaml
- helm-chart/renku/templates/graph/event-log-deployment.yaml
- helm-chart/renku/templates/graph/knowledge-graph-deployment.yaml
- helm-chart/renku/templates/graph/token-repository-deployment.yaml
- helm-chart/renku/templates/graph/triples-generator-deployment.yaml
- helm-chart/renku/templates/graph/webhook-service-deployment.yaml
- helm-chart/renku/templates/search/search-api-deployment.yaml
- helm-chart/renku/templates/search/search-provision-deployment.yaml
Also add the certificates init-container to search-api and search-provision.
Thanks to @JGodin-C2C for reporting the issue.
/deploy
> fix: Set the correct path of CA certs for OpenJDK based containers.

- CHANGELOG.rst
- helm-chart/renku/values.yaml
> fix: bump notebooks to 1.26.2

- CHANGELOG.rst
- helm-chart/renku/values.yaml
> feat: update renku UI 3.38.0

- CHANGELOG.rst
- docs/spelling_wordlist.txt
- helm-chart/renku/templates/notebooks/statefulset.yaml
- helm-chart/renku/values.yaml
- helm-chart/values.yaml.changelog.md
> notebooks release 1.27.1

- CHANGELOG.rst
- helm-chart/renku/values.yaml
* Better support for connecting to GitHub
* Some UX improvements to the UI
/deploy
> feat: improve UX and better support GitHub connections

- CHANGELOG.rst
- helm-chart/renku/requirements.yaml
> fix: updgrade csi rclone to 0.3.5

- helm-chart/renku/templates/network-policies.yaml
NOTE: the target branch is a feature branch.
@leafty I have not tested this but I am pretty sure it will work. If you want you can test here and then merge. Up to you.
> chore: network policies for v2 secrets mounting

- CHANGELOG.rst
- helm-chart/renku/requirements.yaml
> fix: upgrade amalthea to 0.14.7

- CHANGELOG.rst
- helm-chart/renku/templates/search/search-api-deployment.yaml
- helm-chart/renku/templates/search/search-provision-deployment.yaml
- helm-chart/renku/values.yaml
- helm-chart/values.yaml.changelog.md
> Update search to 0.7.0

- CHANGELOG.rst
- helm-chart/renku/values.yaml
Introduce a refreshed design for the user and group pages.
/deploy
> feat: update user and group pages design

- CHANGELOG.rst
- helm-chart/renku/values.yaml
> fix: bump renku-data-services to 0.29.0

- CHANGELOG.rst
- helm-chart/renku/values.yaml
Merge the copy-projects feature
/deploy
> chore: update renku-ui to 3.45.0

- CHANGELOG.rst
- helm-chart/renku/values.yaml
> chore: update renku-ui to 3.46.1

- .github/workflows/cron-jobs.yaml
- .github/workflows/publish-helm-chart.yml
- .github/workflows/publish-master-merges.yaml
- .github/workflows/pull-request-test.yml
- .github/workflows/renku-dev-test.yaml
- CHANGELOG.rst
- helm-chart/renku/requirements.yaml
> fix: update csi rclone to 0.3.6 (#3889)

- CHANGELOG.rst
- docs/spelling_wordlist.txt
- helm-chart/renku/requirements.yaml
- helm-chart/renku/values.yaml
> feat: update data service to 0.32.0, csi rclone to 0.3.7

- .github/workflows/pull-request-test.yml
- cypress-tests/cypress/e2e/v2/groupBasics.cy.ts
- cypress-tests/cypress/e2e/v2/projectBasics.cy.ts
- cypress-tests/cypress/e2e/v2/projectResources.cy.ts
- cypress-tests/cypress/support/types/project.types.ts
See title
/deploy renku-ui=lorenzo/cypress-renku-2.0-data-cy
fix https://github.com/SwissDataScienceCenter/renku/issues/3887
> Add a cypress test for testing project resources: work with code, data, environments

- CHANGELOG.rst
- helm-chart/renku/values.yaml
> feat: upgrade data services and gateway

- helm-chart/renku/templates/data-service/deployment.yaml
- helm-chart/renku/values.yaml
Related PR: https://github.com/SwissDataScienceCenter/renku-data-services/pull/657
> define retention parameters

- CHANGELOG.rst
- docs/spelling_wordlist.txt
- helm-chart/renku/templates/notebooks/env-secret.yaml
- minimal-deployment/minimal-deployment-values.yaml
> feat: Define more sensible default in chart

- helm-chart/renku/templates/data-service/deployment.yaml
- helm-chart/renku/values.yaml
tested in https://github.com/SwissDataScienceCenter/renku-data-services/pull/674
> feat: allow setting timeouts for builds

- CHANGELOG.rst
- helm-chart/renku/templates/data-service/cronjobs.yaml
- helm-chart/renku/templates/data-service/deployment.yaml
- helm-chart/renku/templates/network-policies.yaml
- helm-chart/renku/values.yaml
- helm-chart/values.yaml.changelog.md
> Configure data-services to connect to solr

- .github/workflows/pull-request-test.yml
- cypress-tests/cypress/e2e/v2/sessionBasics.cy.ts
See title.
/deploy renku-ui=main
fix https://github.com/SwissDataScienceCenter/renku/issues/3907
> Add a Cypress test to check sessions run correctly

- CHANGELOG.rst
- helm-chart/renku/templates/data-service/deployment.yaml
- helm-chart/renku/templates/network-policies.yaml
- helm-chart/renku/values.yaml
- helm-chart/values.yaml.changelog.md
> revert: Configure data services to connect to solr

- .github/workflows/auto-reqs-update-pr.yml
- .github/workflows/check-acceptance-test-code.yml
- .github/workflows/check-acceptance-test-fmt.yml
- .github/workflows/create-release-branch.yml
- .github/workflows/cron-jobs.yaml
- .github/workflows/github-project.yml
- .github/workflows/publish-helm-chart.yml
- .github/workflows/publish-master-merges.yaml
- .github/workflows/pull-request-test.yml
- .github/workflows/release-test.yml
- .github/workflows/renku-dev-test.yaml
NOTE: This is merging straight into `master`.
/deploy
> chore: update all actions to use ubuntu-24.04

- CHANGELOG.rst
- helm-chart/renku/templates/data-service/rbac.yaml
- helm-chart/renku/templates/notebooks/deployment.yaml
- helm-chart/renku/templates/notebooks/role.yaml
- helm-chart/renku/values.yaml
> fix: make the helm charts work when the feature is not enabled

- CHANGELOG.rst
- helm-chart/renku/requirements.yaml
> chore: bump amalthea to 0.17.0

- CHANGELOG.rst
- cypress-tests/cypress/e2e/v2/anonymousNavigation.cy.ts
- cypress-tests/cypress/e2e/v2/projectBasics.cy.ts
- helm-chart/renku/values.yaml
> fix: update data services to 0.35.2

- CHANGELOG.rst
- helm-chart/renku/values.yaml
PR support migrate projects from Renku v1 to Renku 2.0
> feat: add project migration from Renku v1 to Renku 2.0

- .github/workflows/cron-jobs.yaml
- .github/workflows/publish-helm-chart.yml
- .github/workflows/publish-master-merges.yaml
- .github/workflows/pull-request-test.yml
- .github/workflows/renku-dev-test.yaml
> chore: bump renku-actions to 1.17.0

- CHANGELOG.rst
- helm-chart/renku/templates/data-service/deployment.yaml
- helm-chart/renku/templates/network-policies.yaml
- helm-chart/renku/values.yaml
- helm-chart/values.yaml.changelog.md
This re-enables configuration for data-services to access solr.
It is re-reverting PR #3934
> feat: Enable accessing solr from data-services

- CHANGELOG.rst
- helm-chart/renku/values.yaml
> build: bump renku-ui to 3.53.0

- CHANGELOG.rst
- helm-chart/renku/values.yaml
> Fix linking data connectors from projects

- CHANGELOG.rst
- helm-chart/renku/values.yaml
> chore: update keycloak theme image to 4.1.6

- CHANGELOG.rst
- docs/spelling_wordlist.txt
- helm-chart/renku/values.yaml
> fix: upgrade renku-data-services to 0.38.0

- CHANGELOG.rst
- scripts/harbor-init/README.md
- scripts/harbor-init/go.mod
- scripts/harbor-init/harbor-init.go
This commit adds an initialization script to configure a Harbor instance to be used as image registry for Renkulab v2.
> feat: Add init script for Harbor.

- .github/workflows/pull-request-test.yml
- cypress-tests/cypress/support/commands/login.ts
> fix: wait for authorize button

- cypress-tests/cypress/e2e/useSession.cy.ts
- cypress-tests/cypress/support/commands/sessions.ts
> fix: legacy acceptance tests

- CHANGELOG.rst
- helm-chart/renku/templates/data-service/deployment.yaml
- helm-chart/renku/templates/data-service/deployment_data_tasks.yaml
- helm-chart/renku/templates/data-service/deployment_k8s_watcher.yaml
- helm-chart/renku/templates/gateway/deployment-revproxy.yaml
- helm-chart/renku/values.yaml
- helm-chart/values.yaml.changelog.md
/deploy #notest extra-values=posthog.enabled=true,posthog.apiKey=phc_9KXbWU5fPFWJeBQa6n53deAJJKfjqedLJHhMohutDS1,posthog.host=https://eu.i.posthog.com,posthog.environment=development
> feat: add posthog to data services

- cypress-tests/cypress/e2e/v2/projectResources.cy.ts
- cypress-tests/cypress/e2e/v2/sessionBasics.cy.ts
PR to fix e2e tests after session improvement changes
/deploy renku-ui=andrea/other-session-improvements
> fix(test): remove action targeting non-existent environment-advanced-settings-toggle

- CHANGELOG.rst
- helm-chart/renku/templates/data-service/deployment_k8s_watcher.yaml
- helm-chart/renku/values.yaml
> fix: disable k8s caching of image builders if they are disabled

- CHANGELOG.rst
- helm-chart/renku/values.yaml
This fixes a failing DB migration in the user preferences table.
/deploy
> fix: update data service to 0.43.2

- CHANGELOG.rst
- docs/spelling_wordlist.txt
- helm-chart/renku/values.yaml
> feat: upgrade data services to 0.44.0

- CHANGELOG.rst
- helm-chart/renku/values.yaml
Note: the ui release process is still underway I will add the deploy string shortly.
/deploy
> feat: add jupyterlab as option for buildpacks

- helm-chart/renku/values.yaml
Remove hardcoded defaults for args and command for environments built from code.
> fix: upgrade data services to 0.47.1

- helm-chart/renku/values.yaml
> feat: upgrade data services to 0.48.1

- helm-chart/renku/values.yaml
> feat: upgrade ui to 4.2.0

- helm-chart/renku/values.yaml
> feat: upgrade data service to 0.50.0

- .github/workflows/pull-request-test.yml
- helm-chart/renku/templates/ui/ui-client-ingress.yaml
- minimal-deployment/minimal-deployment-values.yaml
> feat: Default to deploy CI on Azure

- helm-chart/renku/values.yaml
> fix: upgrade data services to v0.53.2

- minimal-deployment/minimal-deployment-values.yaml
> feat: Disable V1 services in CI deployments.

- global-images/README.md
> chore(global-images): fix readme table formatting

- helm-chart/renku/requirements.yaml
- feat: better error handling for node auto scaling
- fix: idleness checks that are based on network requests
/deploy
> feat: update amalthea 0.21.0

- minimal-deployment/minimal-deployment-values.yaml
We missed one redis image.
/deploy
> chore: update minimal values to use bitnami image

- .github/workflows/cron-jobs.yaml
- .github/workflows/publish-helm-chart.yml
- .github/workflows/publish-master-merges.yaml
- .github/workflows/pull-request-test.yml
Fixes the renku teardown action.
> build: update renku-actions to v1.19.1

- helm-chart/renku/values.yaml
/deploy
NOTE: This should be merged before #4191.
> feat: update renku-data-services to v0.57.0

- helm-chart/renku/values.yaml
> feat: upgrade ui to 4.9.0

- docs/docs/10-users/20-getting-started/70-conclusion.md
- docs/docs/10-users/20-getting-started/_01-full-tutorial.md
- docs/docs/10-users/30-projects/00-projects.md
- docs/docs/10-users/30-projects/guides/10-create-a-project.md
- docs/docs/10-users/60-sessions/guides/_90-create-custom-environment-and-launcher-for-shiny-app.md
- docs/docs/10-users/60-sessions/guides/_99-set-up-shiny-app-launcher.md
- docs/docs/10-users/70-collaboration/20-permissions.md
- docs/docs/10-users/80-use-cases/20-teaching/30-set-up-course-in-advanced-mode-using-git.md
- docs/docs/10-users/80-use-cases/35-groups.md
- docs/docs/10-users/80-use-cases/40-showcase-your-project-on-renku.md
- docs/docs/10-users/85-migrate-v1-v2/10-migrate-renku-1-project-to-renku-2.md
- docs/docs/10-users/85-migrate-v1-v2/20-migrate-from-gitlab/20-migrate-session-launcher-that-references-renku-gitlab.md
- docs/docs/10-users/85-migrate-v1-v2/20-migrate-from-gitlab/40-migrate-code-repository-out-of-renkulab-gitlab.md
I also started fixing linting errors and putting #TODOs where I see things that need to be fixed
> Remove references to 2.0 and v2
