- docker-compose.yml
- docs/developer/code_repo_structure.rst
> Moving ui image to renga-ui and fixing corresponding doc

- docs/user/setup.rst
docker-compose is not installed with docker, unlike on mac.
> Added docker-compose as a prerequisite

- docs/_static/uml/multi_resource_example.uml
- docs/developer/general/json_web_tokens.rst
- docs/developer/general/policy_based_access_controls.rst
- docs/developer/services/explorer_service.rst
- docs/developer/services/knowledge_graph.rst
- docs/developer/services/projects_service.rst
- docs/developer/services/resource_manager_service.rst
- docs/developer/services/services_architecture.rst
- docs/developer/services/storage_service.rst
- docs/index.rst
- docs/introduction/index.rst
- docs/user/firststeps.rst
- docs/user/setup.rst
- docs/user/troubleshooting.rst
* reformat all pages to common width (79 + newline)
* add multi-resource seq. diagram example
* add note about mac os x memory requirements
* replace :code: with ``
closes #94  
closes #96
> docs reformatting

- Makefile
- docker-compose.yml
- services/keycloak/docker-entrypoint.sh
- services/keycloak/renga-realm.json.tpl
Note: UI is still served by webpack dev server so far - not suitable for production.
- Fix keycloak login for gitlab
- Preregister gitlab and the ui as keycloak clients
- Preregister ui as oauth client with gitlab
- Add ui as a service to docker-compose
--
addresses #117
> Configure Renga repository for new ui

- Makefile
- services/keycloak/renga-realm.json.tpl
Added http://localhost:3000 as allowed renga-ui client url  to gitlab and keycloak setup for a better ui development setting.
> Adapt ui client urls for dev setting

- Makefile
So that we don't have to read the file to guess the variables.
> added env target

- Makefile
- docker-compose.yml
- scripts/wait-for-services.sh
The PR:
* removes references to `localhost`and `docker.for.mac.localhost` and instead uses `renga.local` as the default domain for development 
* the developer must add `renga.local`, `gitlab.renga.local` and `keycloak.renga.local` to `/etc/hosts` in order for the names to resolve. 
* Traefik uses host-based rules instead of prefix-based. 
---
addresses #117
> eliminate using localhost everywhere

- services/keycloak/renga-realm.json.tpl
Allow the username to differ from the email address in keycloak.
> Change keycloak renga realm setting

- docker-compose.yml
- services/jupyterhub/project_service.py
- services/jupyterhub/spawners.py
- services/notebook/gitlab_commit_push.py
Modify the docker spawner to launch notebooks with a custom image. The image name/tag is based on the notebook URL naming scheme. The image has to be built manually for now, see the todo list in #176.
---
addresses #176
> jh: launch notebooks with custom image if present

- charts/README.rst
Otherwise it uses an old image.
> build docker images in the minikube

- services/jupyterhub/spawners.py
> charts: add missing command in kube spawner

- Makefile
- charts/renga/charts/gitlab/templates/_gitlab.rb.tpl
- docker-compose.yml
- services/keycloak/renga-realm.json.tpl
- tests/test_renga.py
the `demo` user is made an admin. Could not create an additional `admin` user as this is a protected username in gitlab. 
Not sure if this is related: cannot log out of gitlab until I delete the `keycloak.renga.build` application data. 
---
closes #185
> Do not show the gitlab login page

- Makefile
Removes direct access to GitLab database.
---
see also #208
> Makefile: use GitLab API to configure Auto-DevOps

- charts/minikube-values.yaml
- charts/renga/requirements.yaml
- charts/renga/templates/configmap.yaml
- charts/renga/templates/post-install-job.yaml
- charts/renga/templates/secrets.yaml
- charts/renga/values.yaml
This adds the sudo token needed for certain API actions and creates the sudo user in gitlab. 
This is critical if we want to have admin access in gitlab if we only use keycloak for login.
> Add sudo gitlab token and configure sudo user in init script

- services/jupyterhub/spawners.py
- services/singleuser/gitlab_commit_push.py
Not using the `env-slug` anymore broke the gitlab commit and push button in our custom Jupyter notebook. This restores the functionality. 
closes #226
> jh: do not use env-slug for branch name

- charts/README.rst
Recommend to run minikube with 6 GB of memory. The default of 2 GB (v0.27.0) doesn't seem to be nearly enough for renku.
> Specify minikube memory in README.rst

- charts/renku/requirements.yaml
- charts/renku/values.yaml
- services/jupyterhub/jupyterhub_config.py
- services/jupyterhub/spawners.py
- services/notebooks/notebooks_service.py
pod names are now, e.g.: 
```
jupyter-cramakri--f590027
```
closes #248
> shorten server names to avoid >63 character pod names

- charts/renku/values.yaml
Documents the `sshPort` settings in `values.yaml`
> Added missing documentation for gitlab ssh port

- scripts/travis-install.sh
This gets rid of building all images from scratch on cron jobs. Not necessary at the moment and it's causing problems with disk space on travis.
> ci: remove image builds on cron jobs

- charts/renku/values.yaml
The JH chart v0.6 doesn't have a `debug` value setting, so we need to turn on debugging in the JH options. 
Also, since fixing the slow spawn timeout in `renku-notebooks`, we should set the corresponding timeout here for the `KubeSpawner`.
> JH configuration update

- charts/renku/charts/gitlab/templates/_gitlab.rb.tpl
- charts/renku/charts/gitlab/values.yaml
- charts/renku/values.yaml
This PR allows to setup remote LFS objects in GitLab.
Docs: https://docs.gitlab.com/ce/workflow/lfs/lfs_administration.html
This is useful to avoid filling up the persistent disk with lfs objects.
This has been tested on staging, with objects pushed to a designated OpenStack Swift container.
> Introduce settings for external LFS objects

- charts/renku/charts/gitlab/templates/_gitlab.rb.tpl
- charts/renku/charts/gitlab/values.yaml
The `default` primitive from the go template engines is not acting as expected, so the default is set explicitly.
Also, change the case for consistency.
> Fix backend health check

- docker-compose.yml
- scripts/renku-start.sh
- services/jupyterhub/spawners.py
Change configuration to allow use of images built by CI. See https://github.com/SwissDataScienceCenter/renku-python/issues/207 for details on the CI setup needed. 
Note that the spawner mixins need to be refactored (right now there is some redundant code) because the image spec is named differently between `DockerSpawner` and `KubeSpawner` -- but this should happen when we upgrade the JH version to 0.9 because the naming is different there. 
---
closes #176
> configure image builds

- services/jupyterhub/requirements.txt
python-gitlab 1.5.0 was released and it seems to have a broken API (https://github.com/python-gitlab/python-gitlab/issues/537) -- pin the version to 1.5.1. Tested on staging.
> jh: pin python-gitlab version

- charts/README.rst
After fresh install of helm, one also has to add the jupyterhub repository.
> Added missing step to minikube first steps documentation.

- charts/renku/charts/gitlab/templates/deployment.yaml
Wrong probe makes service unreachable.
> Increase timeout for gitlab

- charts/renku/charts/gitlab/templates/registry-service.yaml
- charts/renku/requirements.yaml
- charts/renku/values.yaml
- scripts/minikube_deploy.py
Image building and notebook launch button work out of the box with `make minikube-deploy`.
The registry url uses the in cluster IP as a way to achieve this.
~~TODO:~~
~~- [ ] add doc for `.gitlab-ci.yml`~~
Closes #327 
~~Making the gitlab registry work properly is still not simple, so recommended to simply not use it in `.gitlab-ci.yml`:~~
```yaml
image_build:
stage: build
image: python:3.6
before_script:
- curl -sSL https://get.docker.com/ | sh
script:
- CI_COMMIT_SHA_7=$(echo $CI_COMMIT_SHA | cut -c1-7)
- docker build --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA_7 .
tags:
- image-build
```
~~As the image is built in minikube, the image is available for JH.~~
> Use docker executor for gitlab runner

- docs/developer/minikube.rst
While developing on minikube, there's a high chance of encountering disk pressure on minikube.
> [docs] Recommend disk size 40g for minikube

- charts/keycloak/templates/_renku-realm.tpl
Remove localhost URLs from the list of allowed hostst/redirectURLs (used for local dev) in the renku realm template.
Closes #340
> Remove localhost from keycloak realm template

- docs/requirements.txt
This builds the doc against my patch of the sphinx graphviz extension, which enables relative paths in custom node images (i.e. the icons actually show up). See https://renku.readthedocs.io/en/fix-324/user/reproducibility.html
The patch has been submitted as a PR to sphinx.
> docs: use patched sphinx until upstream PR is merged

- services/singleuser/Dockerfile
Because at times, some python packages have system dependencies.
Example:
```bash
$ pip install opencv-python
[...]
Successfully installed numpy-1.15.0 opencv-python-3.4.2.17
$ python -c "import cv2"
[...]
ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory
```
Need to run:
```bash
$ sudo apt update && sudo apt install -y python-opencv
```
Of course, we'd still recommend to add the `apt install` to the Dockerfile, but it's not nice to have to fully
cycle a jupyter server and wait for an image build to install things.
> singleuser: Make jovyan sudoer

- charts/renku/values.yaml
closes #370  and https://github.com/SwissDataScienceCenter/renku-notebooks/issues/27 -- however, beware that this brings up new problems. For example jupyterlab introduces the idea of workspaces, which seems to conflict a bit with our concept of tying a server to a git commit. Right now, if you try to launch two different jupyterlab sessions for two different commits in your history you will be asked to switch to a different workspace -- at which point you will redirect to an incorrect URL (doesn't take into account the `base_url` from jupyterhub -- bug report?)
> jh: use jupyterlab

- scripts/run-tests.sh
@leafty Looks to me like the docker pull is not necessary and we can shorten the build a bit. Or am I missing something?
> Let tests always pull the latest renku-demo image

- charts/minikube-values.yaml
`securityContext` is on by default -- this disables it for minikube to allow telepresence development.
> charts: disable security context for allowing telepresence

- scripts/minikube_deploy.py
- tests/Dockerfile
- tests/test_renku.py
Update the dependencies of the sub-charts (currently only relevant for notebooks service) before packaging the renku chart in the `minikube-deploy` script.
Solves the problem that the jupyterhub service was not included in the minikube deployment unless the renku-notebooks dependencies had been added manually at some point before.
> Update sub-chart dependencies in minikube-deploy

- charts/minikube-values.yaml
- charts/renku/values.yaml
Set the renku version (affecting the template used in project creation) to latest for minikube deployments. Does currently not affect anything than project creation.
> Set renku version to 'latest' for minikube deployments

- charts/minikube-values.yaml
- charts/renku/templates/ingress.yaml
- charts/renku/values.yaml
- scripts/travis-install.sh
See: https://gitlab.com/gitlab-org/gitlab-workhorse/issues/130
`proxy-request-buffering` is disabled in GitLab, for pushing LFS objects as it caused issues.
The ingress (`nginx`) has it on by default.
> Fix for large lfs objects

- charts/chartpress.yaml
- charts/gitlab/Chart.yaml
- charts/gitlab/requirements.lock
- charts/gitlab/requirements.yaml
- charts/gitlab/templates/_gitlab.rb.tpl
- charts/gitlab/templates/_helpers.tpl
- charts/gitlab/templates/deployment.yaml
- charts/gitlab/values.yaml
- charts/renku/Chart.yaml
- charts/renku/requirements.lock
- charts/renku/requirements.yaml
- charts/renku/templates/_helpers.tpl
- charts/renku/values.yaml
by resolving redis.fullname in a sort of scoped namespace. Once the related helm issue (https://github.com/helm/helm/issues/4535) is solved, we can also clean the other re-definitions of fullnames.
> Allow for having multiple redis instances

- scripts/minikube_deploy.py
Run `helm dep update` also on the gitlab chart of renku.
> Fix minikube deploy after allowing multiple redis instances

- docs/user/cli-installation.rst
- docs/user/firststeps.rst
- docs/user/git_tips.rst
- docs/user/index.rst
- docs/user/lfs.rst
Improves the user documentation including:
* info about how to install into an isolated environment with conda
* some first instructions to use git-lfs
* git tips
* add a note about `renku rerun` to the first steps 
addresses #452 
addresses #343
> add info about git and git-lfs to docs

- charts/minikube-values.yaml
Fix the postgres password in the url used by jupyterhub to connect to postgres.
Note: This  works, however it's not very elegant to just copy paste a value from another line in `minikube-values.yaml`. On the other hand, values files are not templateable themselves... Is there a better way to do this?
> Fix minikube-values.yaml

- charts/minikube-values.yaml
- charts/renku/templates/configmap.yaml
Unfortunately gitlab "redirect after logout" is a global setting. So either it works nice with the Renku UI (redirecting to the renku home page) or it works nice when using gitlab only (redirecting to gitlab's home page and potentially directly to keycloak login again).
> Fix logout for Renku and missing value

- charts/renku/values.yaml
Commented out expressions were causing problems when chartpress updated the values.yaml file. The resulting file was no longer valid yaml. The offending expressions were moved to their own lines where they do not cause any problems.
> Fix a problem in the interaction between chartpress and values.yaml

- charts/renku/values.yaml
It was too short, so keycloak mey not have the time to start
> [chart] increase timeout for keycloak readiness probe

- scripts/run-tests.sh
- tests/test_renku.py
helm test is failing seemingly due to a timeout. Try to increase it or remove the notebook test altogether.
> fix travis tests

- charts/renku/templates/ingress.yaml
I reminded a suggestion that `webhook-service`'s endpoints names are a bit broken. I fixed that as I think it's easier to do it now.
> Fixed naming of the webhook-service's event consuming endpoint

- charts/example-configurations/minikube-values-gitlab.yaml
- charts/example-configurations/minikube-values-renkulab-template.yaml
- charts/minikube-values.yaml
- charts/renku/values.yaml
This secret I forgot the other day and effectively all the environments would be using the same secret for encrypting the hook tokens send from Gitlab
> Added hookToken.secret value required during webhook-service deployment

- charts/example-configurations/minikube-values-gitlab.yaml
- charts/example-configurations/minikube-values-renkulab-template.yaml
- charts/minikube-values.yaml
- charts/renku/templates/configmap.yaml
- charts/renku/templates/secrets.yaml
- charts/renku/values.yaml
This change is to make https://github.com/SwissDataScienceCenter/renku-graph/pull/59 compatible with `renku`.
> DB Event Log instead of File Event Log for Graph

- charts/renku/Chart.yaml
- charts/renku/values.yaml
Unquoted `nginx.ingress.kubernetes.io/proxy-request-buffering: off` potentially results in problematic rendering by YAML 1.2 parsing, exposing us to issues such as:
* Un-quoted "on" and "off" strings evaluated as true/false in values.yaml
ref. https://github.com/helm/helm/issues/5497
Namely, when this value is unquoted `off` it can be interpreted as `false`, then nginx cannot digest it and it results in service suppression.
p.s. the icon 1 line diff in `renku/Chart.yaml` is cosmetic, I merely avoid a trivial PR.
> hotfix against YAML 1.2 rendering issues for renku.yaml

- docs/spelling_wordlist.txt
- docs/user/autosave.rst
- docs/user/index.rst
Basic documentation to explain how the autosave feature on JupiterLab works.
In the future, it may be a good idea to name the page `JupiterLab` and to add some general information, moving the autosave stuff to a sub-paragraph.
closes #590 
required by SwissDataScienceCenter/renku-ui#507
> docs: add basic autosave docs

- charts/gitlab/Chart.yaml
- charts/renku/requirements.lock
- charts/renku/requirements.yaml
- charts/renku/values.yaml
https://swissdatasciencecenter.github.io/helm-charts/renku-0.4.1-rc2.tgz is deployed on https://limited.renku.ch -- seems to be fine, upgrade was mostly trivial apart from adjusting a few values. 
closes #603
> Prep 0.4.1

- docs/spelling_wordlist.txt
- docs/user/collaboration.rst
- docs/user/firststeps.rst
- docs/user/index.rst
I added an extra page with a few subheadings on how to interact with projects owned by other people, and linked this page from the "Users" table of contents.
I spot-checked this to see if any of this was written anywhere else, but someone more familiar might have a better idea.
> docs: added collaboration docs

- .github/ISSUE_TEMPLATE/new-release.md
This adds a "new release" template with a checklist for making a new renku release.
> chore: create a "new release" template

- Makefile
- scripts/minikube_deploy.py
The `chartpress.yaml` file has been moved outside of the `helm-charts` directory in `renku-notebooks` recently. As a result, `make minikube-deploy` fails because `chartpress.yaml` is not found. This PR fixes the problem.
> Allow chartpress.yaml to be outside of chart directory

- charts/renku/requirements.lock
- charts/renku/requirements.yaml
- charts/renku/templates/_keycloak-clients-users.tpl
This PR renames the the "gateway" client application in Keycloak to "renku".
Merge right after https://github.com/SwissDataScienceCenter/renku-gateway/pull/176.
Closes #519 and #641.
> Rename main renku client in Keycloak

- Pipfile
- Pipfile.lock
pin chartpress version to avoid using the new charts naming convention
> build: pin chartpress version

- docs/user/firststeps.rst
The link was pointing to `cli.html` but the page is called `commands.html` now.
> fix: Changes URL to renku-python commands documentation page

- charts/renku/Chart.yaml
- charts/renku/requirements.lock
- charts/renku/requirements.yaml
- charts/renku/templates/_helpers.tpl
- charts/renku/values.yaml
Adds the renku core-service to the deployment. 
closes #709
depends on https://github.com/swissdatasciencecenter/renku-python/issues/772 and https://github.com/swissdatasciencecenter/renku-gateway/issues/180
> build: add renku-core-service

- charts/gitlab/templates/_gitlab.rb.tpl
- charts/gitlab/values.yaml
This turns on gitlab json logging for all services. From gitlab 12.x this is anyway the default in which case these options will not be needed.
> build: enable gitlab json logging

- charts/renku/values.yaml
- charts/values.yaml.changelog.md
This PR adds basic info to `charts/renku/values.yaml` about the new `ui.sentry` settings. Related to SwissDataScienceCenter/renku-ui#761
> chore: add ui sentry info

- charts/renku/templates/ingress.yaml
This PR adds an ingress rule which forwards traffic from `/entities` to the gateway.
Currently deployed together with https://github.com/swissdatasciencecenter/renku-gateway/issues/174 under https://andreas.dev.renku.ch
> feat: add ingress rule for /entities

- README.rst
The readme is shared between this repo and the front page of the renku sphinx docs -- we forgot to make the links github-page friendly.
> fix: readme links full path

- docs/getting_started.rst
- docs/tutorials/courses.rst
We already have a "getting started" tutorial for using the renku CLI inside renkulab, but we didn't have docs to answer common questions for how people can create/add course material on renku.
> docs: adding docs for courses

- CHANGELOG.rst
- charts/renku/Chart.yaml
- charts/renku/requirements.lock
- charts/renku/requirements.yaml
- charts/renku/templates/NOTES.txt
- charts/renku/templates/anonymous-notebooks-namespace.yaml
- charts/renku/templates/configmap.yaml
- charts/renku/templates/jupyterhub-tmp-postgres-secret.yaml
- charts/renku/templates/post-install-job-postgres.yaml
- charts/renku/values.yaml
- charts/values.yaml.changelog.md
- docs/admin/index.rst
- docs/spelling_wordlist.txt
This PR adds the chart changes necessary to enable anonymous interactive environments. Only merge after
have been merged.
Deployments with all these changes are running under:
https://tmp-on.dev.renku.ch/ (anonymous sessions enabled)
https://tmp-off.dev.renku.ch/ (anonymous sessions disabled)
> Modify Renku chart to enable anonymous notebook sessions (optional)

- .github/workflows/pull-request-teardown.yml
- .github/workflows/pull-request-test.yml
This will make it easier to identify a ci namespace for a given PR.
> ci: use PR number in ci release name

- .github/workflows/pull-request-test.yml
This will allow documentation reviewers to directly download the compiled docs from the actions page.
> Add compiled docs to test artifacts

- .github/workflows/remove-old-artifacts.yaml
Looks like it's doing the job. The first attempt with a version that also triggered "on PR" deleted many artifacts.
> Periodically remove old github actions artifacts

- charts/gitlab/Chart.yaml
- charts/gitlab/values.yaml
- charts/renku/requirements.yaml
- charts/renku/values.yaml
GitLab versions >= 12.9.0 require a different logout behaviour from the side of client applications, therefore we also have to update the gateway.
**Merge this PR instead of the auto-generated one after merging https://github.com/SwissDataScienceCenter/renku-gateway/pull/202**
Note that I've built and pushed the gitlab chart `0.5.0` to break the circular versions dependency created by the fact that the gitlab chart is a dependency of the renku chart and also part of the same repo...
> Bump gitlab and gateway versions

- .github/workflows/pull-request-teardown.yml
Renkubot doesn't have the permission to remove namespaces, therefore these lines are failing.
> ci: remove broken steps in PR-teardown

- .github/workflows/deploy.yml
- .github/workflows/pull-request-test.yml
- charts/chartpress.yaml
- tests/docker-compose.yml
I wanted to try out the more advanced caching features that the new docker build kit offers and quickly applied this to our test setup. This PR uses the `renku/tests:latest` during the `sbt` build, thus shortening the tests by a few minutes. It relies on `renku/tests:latest` being built by the new docker build kit.
> ci: speed up tests by avoiding build

- .github/workflows/deploy.yml
It seems to me that failures on our master branch often go unnoticed and are not treated with the appropriate amount of urgency.
> Notify slack when tests fail on CD deployment

- charts/gitlab/Chart.yaml
- charts/gitlab/requirements.lock
- charts/gitlab/requirements.yaml
- charts/renku/requirements.yaml
Addresses parts of https://github.com/SwissDataScienceCenter/renku/issues/1271.
Note that the gitlab 0.5.2 chart according to this PR has already been built and published manually. Should there be any changes the published chart would have to be deleted and recreated.
> Bump redis chart version in gitlab chart

- charts/renku/values.yaml
This removes the continuous image puller, the user scheduler and the user placeholder deployments. They are not needed in our default configuration.
> build: remove jh optimizations

- .gitignore
The `.vscode` folder was included in the gitignore but some specific files (the most relevant once) were excluded. Not sure if this is on purpose or it's just a leftover, but this PR excludes all the folder -- as in the other renku repositories.
> chore: add vscode to gitignore

- charts/renku/requirements.yaml
- charts/renku/values.yaml
- charts/values.yaml.changelog.md
If minio is needed, it should be deployed outside of Renku.
> chore(charts): remove minio from dependencies

- charts/minikube-values.yaml
These details have been provided through the command line in the past, however the IP is hardcoded in the nodeport service template of the gitlab chart anyway.
> fix(charts): fix registry detail in minikube values

- tests/Dockerfile
Pin `nbconvert` to solve incompatibility with `papermill`
> chore: pin nbconvert dependency

- .github/workflows/autoupdate.yaml
This PR adds the sibling of `automerge`. Set both the `autoupdate` and `automerge` label on an accepted PR and let the 🤖 do the rest.
> chore(ci): add possibility to auto-update PRs

- .github/workflows/deploy.yml
Adding this _should_ allow us to manually trigger the CD pipeline on the non-default branch. See [the github actions docs](https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads#workflow_dispatch).
> chore(cd): add manual trigger for CD pipeline on any branch

- docs/conf.py
There was an error in the relative path in `docs/conf.py` that meant docs failed to build on tags. This change has been used on the 0.7.x branch (see build [here](https://readthedocs.org/projects/renku/builds/12250687/)).
> docs: fix relative path to reqs

- .github/workflows/auto-reqs-update-pr.yml
- .github/workflows/deploy.yml
- actions/update-component-version/update-upstream.sh
This PR changes the CI/CD pipeline to deploy from the `development` branch. The updates are in three places:
* the github action used by repositories --> this is changed to create the PR based on the development branch
* the automatic PR creation action --> this uses `development` as the base branch
* the CD pipeline is deployed using the `development` branch
The idea is that updates are pushed to `development` and occasionally a merge is made back to `master`, which remains the default branch. All development that is not an automatic PR for a dependency update should still go to the `master` branch. However, merges to `master` from `development` should happen when we are approaching a release and they should be squashed so that the number of automatic commits is minimized in the git …
> chore: push automatic dependency updates to development

- README.rst
The CI badge was showing the status of CI from the default branch (master) which no longer runs our CI... this changes it to show the status of the development branch.
> chore: fix CI badge

- docs/spelling_wordlist.txt
- docs/user/interactive_basics.rst
- docs/user/interactive_customizing.rst
- docs/user/templates.rst
Update the Interactive Environments documentation pages, including the feature to pin images (that requires this to the merged SwissDataScienceCenter/renku-ui#1109).
fix #1647
> docs: update interactive environments documentation

- .github/workflows/deploy.yml
- .github/workflows/pull-request-test.yml
- actions/publish-chart/README.md
- actions/publish-chart/publish-chart.sh
- actions/update-component-version/README.md
Helm stable repository has officially moved to https://charts.helm.sh/stable , this PR updates the old deprecated URL in this repository github actions.
> fix: update Helm stable URL

- .github/workflows/pull-request-test.yml
- acceptance-tests/Dockerfile
- acceptance-tests/README.md
- acceptance-tests/docker-compose.yml
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/AcceptanceSpec.scala
- charts/renku/templates/tests/test-renku.yaml
- charts/renku/values.yaml
* Refactor container for acceptance test to include Selenium/chromium-driver
* Modify acceptance tests spec to use chromium-driver within the same container
* Add manifest for `helm test` to use the refactored container in a pod
* Update values.yaml to request the necessary parameters to run the tests
* Update documentation
Part of #1762.
> feat: run acceptance tests through helm test

- .github/workflows/pull-request-test.yml
No need to run acceptance tests on this one… the error was in the check-deploy action, the others didn’t change.
you can see it works: https://github.com/SwissDataScienceCenter/renku/runs/1709330766?check_suite_focus=true#step:3:5
> chore: fix action path

- .github/workflows/auto-reqs-update-pr.yml
This updates the automatic PR workflow such that it adds `/deploy` in the PR body to ensure that deployment + tests run.
> chore: update the auto pr workflow

- .github/workflows/pull-request-test.yml
- acceptance-tests/Dockerfile
- acceptance-tests/README.md
- acceptance-tests/docker-run-tests.sh
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/AcceptanceSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/AnonEnv.scala
- actions/deploy-renku/deploy-dev-renku.py
- helm-chart/renku/templates/tests/test-renku.yaml
- helm-chart/renku/values.yaml
- pyproject.toml
The CI acceptance tests are ran through Helm test. As the tests run in the deployment cluster (rather than the GH action     container) if any test fails the results are packaged, passed into an intermediate S3 bucket in SWITCH engine and then    downloaded in the GH action to be served as an artifact as usual.
Fix #1762.
/deploy
> feat: run GH actions acceptance tests through Helm test

- Pipfile
- Pipfile.lock
`pprint.pp()` used in `deploy-dev-renku.py` was added only in python 3.8.
> chore: bump required python version in Pipfile

- .github/workflows/auto-reqs-update-pr.yml
We removed the development branch so that auto-PRs  could be made directly against the master branch.
> chore: make auto-PRs based on the master branch

- helm-chart/renku/templates/tests/test-renku.yaml
- helm-chart/renku/values.yaml
Not all renkulab deployments have the option to configure an S3 bucket, this PR makes this section optional so that these deployments can still benefit from running tests via Helm.
/deploy
> Make S3 config optional

- .github/workflows/pull-request-test.yml
This would run the action when editing the post -- e.g when adding `/deploy` to run the acceptance tests.
> ci: run deploy and test on edit

- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/ProjectPage.scala
Tests are failing on https://github.com/SwissDataScienceCenter/renku-ui/pull/1228 partly because of #1229 and partly because of changes for that PR.
This branch can be merged into 1229 that then can be merged into master.
> test: update acceptance tests to comply with ui changes for 1229

- .github/workflows/deploy.yml
When running the deploy action for Renku, use helm test to pilot the acceptance test instead of docker-compose.
Depends on swissdatasciencecenter/ops-dev.renku.ch#121
closes #1944
> feat: run Helm test for Renku CD

- docs/requirements.txt
`markupsafe@v1.0` had a problem with the latest `setuptools` preventing the docs from building properly.
> chore: update docs dependencies

- .github/workflows/deploy.yml
- .github/workflows/publish-deploy-staging.yml
- Pipfile
- Pipfile.lock
- actions/publish-chart/Dockerfile
- actions/publish-chart/README.md
- actions/publish-chart/publish-chart.sh
Introduce a new workflow that only triggers on tag push that:
1) Publishes a new Helm Chart for Renku of the version specified in the tag
2) Deploys the newly pushed Chart on Staging
3) Runs the acceptance tests on the deployed Renku instance
Close #1977
> feat: publish chart of tag push, deploy on staging and test

- .github/workflows/deploy.yml
- .github/workflows/publish-deploy-staging.yml
- .github/workflows/pull-request-test.yml
- docs/admin/index.rst
This is more of a bandaid than a permanent fix. We should consider breaking up the test scenarios into individual k8s jobs: https://github.com/SwissDataScienceCenter/renku/issues/2042
/deploy
> chore: increase test timeout

- helm-chart/renku/templates/tests/test-renku.yaml
After merging #2011 the tests run at pretty exactly at 2GB of memory and <= 1 CPU.
/deploy
> charts: adapting resource requests for tests

- docs/user/interactive-running-locally.rst
- docs/user/interactive_environments.rst
This PR adds the docs that demonstrate how a renku-generated image can be used to run a "renkulab" session on another machine. 
closes #2040
> docs: added doc on running sessions locally

- docs/user/interactive-running-locally.rst
This seems to fix the problem reported in #2040 that code blocks are not visible. 
Compare [this](https://renku.readthedocs.io/en/2040-local-interactive-session/user/interactive-running-locally.html) to [this](https://renku.readthedocs.io/en/latest/user/interactive-running-locally.html)
> chore: fix up code blocks

- .github/workflows/deploy.yml
Replace direct calls to Slack's API with notification action.
Gives more information, including link to the commit that triggered the workflow.
> feat: use Slack notification action for Deploy workflow

- actions/deploy-renku/deploy-dev-renku.py
This PR fixes the repo references for the ui-server component and it keeps the target version aligned with the UI component unless anything different id explicitly defined.
P.S. sorry for the messy commit history, I'll squash while merging :grin: 
/deploy renku-ui=1092-uiserver-autoscaling
> ci: fix renku-ui-server in the deploy action

- helm-chart/renku/templates/_keycloak-clients-users.tpl
- helm-chart/renku/templates/ingress.yaml
- helm-chart/renku/templates/swagger.yaml
- helm-chart/renku/values.yaml
This PR adds a swagger UI to the renku deployment to allow testing of API endpoints directly in a live deployment. 
It configures the core and notebooks service specs to be shown - each can be selected via a drop-down. 
Some endpoints (e.g. those of the core service) receive tokens via the gateway. The core service api spec is configured for login via Keycloak - this will retrieve a JWT token to inject into the requests that get routed through the gateway. You must also log in to the renku instance you are testing so that the gateway there has actual tokens to send (the login in swagger doesn't do this for you). For endpoints that do not go through the gateway the spec should define the proper authorization methods (e.g. an API token). 
You can access the api docs under …
> chore: add a swagger UI

- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/LoginPage.scala
Fixes the selector for both old and new GitLab versions in our acceptance tests :crossed_fingers: 
/deploy
> Acceptance tess: fix authorize selector

- docs/user/interactive-running-locally.rst
Small patch to add `ip` argument to the `jupyter lab` command when running sessions locally.
Especially relevant for RStudio users.
> fix: patch docker command for running sessions locally

- actions/update-component-version/Dockerfile
It is necessary to explicitly install six now.
> build: fix update-component-version action

- .github/workflows/pull-request-test.yml
- actions/check-pr-description/action.yaml
- actions/deploy-renku/deploy-dev-renku.py
allows specifying additional values to be passed to a custom deployment via the `extra-values` option:
/deploy renku-ui=0.11.x extra-values=ui.canary.enabled=true,ui.canary.image.repository=renku/renku-ui,ui.canary.image.tag=0.11.11-n044.hbfc2e2b
> chore: additional values for pr deploy

- docs/user/interactive_stopping_and_saving.rst
The instructions for how to save and push back changes pre-dated `renku save`...
> chore(docs): update git instructions

- docs/user/templates.rst
Updates documentation with new template variable `__renku_version__`.
fix #2153 
Depends on SwissDataScienceCenter/renku-python#2145
> document __renku_version__ template parameter

- actions/update-component-version/Dockerfile
The installation of chartpress was failing. It succeeded after I installed `gcc`, `g++` and `make` in the Dockerfile.
> build: fix installation of chartpress

- helm-chart/renku/templates/ingress.yaml
The keycloak ingress port is referenced by its name "http" rather
than a number in the default Keycloak Helm Chart Values.
When using Ingress from the stable API the port for the ingress
must be defined as either "number" or "name" fitting the corresponding
types.
This commit changes "number" to "name" for the Keycloak ingress port.
Tested with:
```
helm template renku --validate ./helm-chart/renku -f <values.file.yaml>
```
> (chore) fix Renku ingress template

- helm-chart/gitlab/Chart.yaml
- helm-chart/renku/requirements.yaml
Note: deploying won't help here as our CI deployments do not include gitlab. However, the gitlab chart 0.6.0 got properly published and doesn't use the beta API anymore in its ingress template.
> chore: bump gitlab chart version

- helm-chart/gitlab/templates/registry-ingress.yaml
Note that this is already part of the published 0.6.0 gitlab chart.
> fix(helm-chart): fix gitlab registry ingress spec

- helm-chart/renku/values.yaml
/deploy
This includes the recent fixes to our base-images / templates and should be included in the upcoming Renku release.
> chore: bump renku project templates version

- acceptance-tests/src/test/scala/ch/renku/acceptancetests/model/commons.scala
With 0.16.1.post1 we released a version that isn't compatible with the acceptance test regex, this fixes that.
> chore: fix acceptance tests to accept X.Y.Z.postN version

- helm-chart/renku/templates/post-install-job-gitlab.yaml
We forgot to clean this up in the repo that introduced amalthea.
> fix(chart): remove unneeded Jupyterhub auth secret from gitlab post install job

- CHANGELOG.rst
- helm-chart/renku/Chart.yaml
- helm-chart/renku/requirements.yaml
Prep for the 0.9.3 release that allows for better notifications from status page to be displayed in the ui.
/deploy
> chore: updates for 0.9.3 release

- helm-chart/renku/templates/_helpers.tpl
This change was removed from the documentation update (#2319) and moved here.
> chore: remove Jupyterhub from helpers helm chart file

- CHANGELOG.rst
- helm-chart/renku/Chart.yaml
Updates for `0.10.1` bug fix release.
(not deploying since all component versions stay the same as the head of master)
> Prepare for 0.10.1 release

- .readthedocs.yaml
- docs/spelling_wordlist.txt
`graphviz` has to be added to the apt configuration of the build environment on RTD in order to build the in-line documentation graphs.
> chore(docs): add graphviz to rtd config

- docs/conf.py
- docs/reference/index.rst
The renku python api docs were dropped accidentally. This PR adds them to the `Reference` section.
> chore: add the renku-python api docs

- .github/workflows/auto-reqs-update-pr.yml
- .github/workflows/automerge.yml
- .github/workflows/autoupdate.yaml
- .github/workflows/publish-deploy-staging.yml
- .github/workflows/pull-request-label.yml
I am not sure what is the difference between the `RENKU_CI_TOKEN` and `RENKUBOT_GITHUB_TOKEN` secrets.
But it seems that some of the permissions for `RENKU_CI_TOKEN` have been removed or the token has been fully disabled. Either way it is much nicer to use an org-level secret.
This should probably fix this problem:
https://github.com/SwissDataScienceCenter/renku/runs/4336151543?check_suite_focus=true
> fix(ci): update github token to org secret

- helm-chart/renku/templates/post-install-job-gitlab.yaml
- helm-chart/renku/templates/post-install-job-keycloak.yaml
- helm-chart/renku/templates/post-install-job-postgres.yaml
/deploy 
This also fixes the problem where a chart name containing a "+" sign (e.g. when deploying a version containing build metadata) would fail to create the post-install jobs.
> (fix) Use the same labels for post-install jobs as other resources.

- acceptance-tests/Dockerfile
- acceptance-tests/docker-run-tests.sh
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/model/commons.scala
This PR fixes problem of CLI version mismatch that occurs between the core and local to the tests version of Renku.
/deploy
> fix: pip upgrade to fix the problem of CLI version mismatch

- helm-chart/README.rst
- helm-chart/renku/values.yaml
- helm-chart/values.yaml.changelog.md
Values and instructions updates to support GitLab `14` and PostgreSQL `12` in renku `0.11.0`.
To be merged after next renku bugfix release and after upgrades are applied on dev.
This has been tested on renkulab-test using renkulab.io's snapshots.
> (feat) GitLab and PostgreSQL upgrades

- .github/workflows/publish-master-merges.yaml
When a PR is merged to the master branch a chart is also published, the version is set to `x.y.z+1-n+1` where `x.y.z` is the latest stable release of Renku and `n` is the latest version created by the job introduced in this PR. If an earlier pre-release version does not exists then it is set to 0.
The workflow also pushes the tag of the just created pre-release, this is necessary for the following workflows to assign the correct, increasing, pre-release number.
The new workflow duplicates somewhat `publish-deploy-staging`, however, at a later time I will take care of consolidating the two, when Staging will also be deployed through Flux.
This supercede #2376.
> (feat) Publish Helm chart on all merges to master.

- .github/workflows/publish-master-merges.yaml
When bumping the pre-release version ignore what comes after the '.', the GitHub action, otherwise, is confused and bumps the patch number instead of the pre-release one.
Replace the 'level' to be increased in the action that bumps the semver to correctly be `prerelease` instead of `prepatch`.
> (fix) Correct bumping of pre-release.

- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/Datasets.scala
Originally tried in #2390 - retries fetching the dataset info page when the dataset _should be_ in the kg already but is not showing up on the page. 
/deploy
> fix: Dataset flow to retry if DS is not visible in UI even if it's in KG

- .github/workflows/pull-request-test.yml
- helm-chart/renku/values.yaml
Limits on acceptance test pods seem to introduce throttling and/or container restarts. Remove the limits to see if this might resolve some of the test failures. 
This PR is testing the resource request value changes proposed here: https://github.com/SwissDataScienceCenter/ops-dev.renku.ch/pull/194
/deploy
> chore: do not limit acceptance test pods

- Pipfile
- Pipfile.lock
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/LoginPage.scala
- chartpress.yaml
- helm-chart/renku/requirements.yaml
- scripts/init-realm/init-realm.py
While the current version of Keycloak is not explicitly affected by Log4shell, it is however safer to ship a more recent version.
/deploy
> chore: upgrade to latest Keycloak chart

- docs/how-to-guides/admin/deploying-renku.rst
Helm init is not used anymore in Helm 3. Helm 2 is no longer supported. Therefore the Helm init command should be removed from the documentation.
> docs: remove helm2 init command

- .github/workflows/publish-helm-chart.yml
- .github/workflows/publish-master-merges.yaml
- .github/workflows/pull-request-test.yml
- acceptance-tests/docker-run-tests.sh
Implements the new test and cleanup actions from https://github.com/SwissDataScienceCenter/renku-actions/pull/16
And also adds continuous mirroring of the acceptance tests artefacts to S3. This way even if the tests timeout or crash or whatever there will always be some artifacts that can be uploaded/added to the github workflow.
In the case when the test artefacts are added to S3 only once the tests are complete there were issues because if the tests time out or crash in some weird way then the artefacts are not uploaded and cannot be found on the github workflow. This should avoid a lot of those scenarios.
> chore(test): add new test and cleanup actions

- certificates/Dockerfile
It seems that the package we used before was just removed fully from the package registry on alpine. 
I pinned the packages that are now available on the package registry. The build now succeeds.
/deploy
> fix: custom ca certs dockerfile

- certificates/Dockerfile
It seems that the packages we previously used and we had pinned are no longer available for alpine.
/deploy
> fix: custom ca certificates image build

- .github/workflows/publish-master-merges.yaml
So the current state of this workflow is such that it grabs the latest tag and it uses that to publish a chart. But the latest tag could be anything.
That is why we got into a situation where a feature tag like `0.0.1-certificates` that I added to a feature branch was picked up and is now used for every merge to master.
This change makes it so that only the latest official release tag is used. See example:
https://github.com/SwissDataScienceCenter/renku/runs/4951186244?check_suite_focus=true
In the example above I commented out the chart publishing and made it run on any push. I will remove these temp changes. But it shows this works as intended.
Here is the weird workflow that got published because of a feature branch tag that should be ignored. …
> fix(ci): use latest release tag on master merges

- .github/workflows/publish-master-merges.yaml
This reverts commit 85618992425258f1d0b1dfb96a9da0a385b91ae3.
Undoing it because after this changes the first digit of the pre-release numbering isn't increased anymore. We have to otherwise fix the problems with wrong tags being used as basis for figuring out the right tag after tagging a non-renku chart from this repo.
> fix(ci): undo recent changes to tag/release numbering

- CHANGELOG.rst
- helm-chart/renku/values.yaml
Release notes for renku version `0.12.0`.
> chore: add 0.12.0 release notes

- acceptance-tests/src/test/scala/ch/renku/acceptancetests/FreeTextDatasetSearchSpec.scala
It happens sometimes that our tests fail as they cannot find the expected values on the UI. In some cases it's might be caused by the UI cache holding stale values. A simple retry was proven to work in other places in the past.
/deploy
> fix: free-text DS search to wait for UI cache to catch up

- helm-chart/renku/templates/_keycloak-clients-users.tpl
- helm-chart/renku/templates/post-install-job-keycloak.yaml
- scripts/init-realm/init-realm.py
> feat(chart): enable device auth grant

- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/ProjectPage.scala
- helm-chart/renku/requirements.yaml
So chartpress has a bug where it labels the image wrong when you update a branch in a PR.
To avoid this bug I had to reopen the PR so that it does not need to be updated against master.
> chore: notebooks 1.5.0, UI 2.1.0 release

- acceptance-tests/src/test/scala/ch/renku/acceptancetests/AnonymousEnvironmentSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/UnprivilegedEnvironmentSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/Environments.scala
This change aims to make the specs verifying Anonymous and Unprivileged environments to be more reliable and not to fail when the configured project does not exist on the deployment where the tests are run.
/deploy
> fix: anonymous and unprivileged env specs more reliable

- CHANGELOG.rst
- helm-chart/renku/Chart.yaml
Release 0.12.6 to fix the pinned image check issue.
> chore:  prep release 0.12.6

- CHANGELOG.rst
- helm-chart/renku/Chart.yaml
Another small bugfix release. I removed the old autosave creation script a little too early. This puts it back so that existing sessions which still use the old autosave can successfully create autosaves (if the need arises). 
I have an issue to fully retire the configmap in a later notebooks release.
> chore: prep release 0.12.8

- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/TopBar.scala
Changes necessary to adapt to new version of reactstrap.
This change allowed the tests to pass on https://github.com/SwissDataScienceCenter/renku-ui/pull/1766.
> tests: fix tests for reactstrap update

- acceptance-tests/src/test/resources/logback.xml
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/GitLabUserProfilePage.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/GitLabWelcomePage.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/Page.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/TopBar.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/AcceptanceSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/GitLabApi.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/WebDriverOps.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/GitLabCredentials.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/Login.scala
This PR adds a special flow to the acceptance tests which sets up GitLab password for the user the tests use for logging in. The main aim of the change is to simplify running tests with a test user that was registered with the standard registration process and so it's lacking GitLab password. The password is used by the tests to obtain an OAuth token that might be used for accessing GitLab API and by the tests' clean-up procedures. The new flow is triggered automatically and it's skipped when an OAuth token is injected into the tests or the tests can already fetch it (which means the GitLab password is already set).
/deploy
> feat: tests to set-up user creds in GitLab if missing

- helm-chart/renku/requirements.yaml
Bitnami have removed 12k+ chart versions from their standard Helm chart repo, including the postgresql and redis chart versions we depend on for the latest renku chart. More details on that [here](https://github.com/bitnami/charts/issues/10539). In order to keep using these chart versions, we need to use Bitnami's pre-2022 versions repo.
> fix(helm): use legacy bitnami repo

- CHANGELOG.rst
- docs/spelling_wordlist.txt
- helm-chart/renku/Chart.yaml
This is a bugfix release for the notebook service.
The most important part of this is that a bug in the notebook service was making it appear as though s3 bucket mounting is not available on any deployment.
This fixes the problem.
> chore: prep 0.12.16 release

- certificates/Dockerfile
- helm-chart/certificates/templates/_init-container.tpl
- helm-chart/certificates/templates/_volumes.tpl
It turns out that with some tweaks to the Dockerfile and permissions of mounted certificates secrets we can run certificate injection as non-root.
> chore: run certificates injection as non-root

- helm-chart/renku/templates/network-policies.yaml
- helm-chart/renku/templates/post-install-job-postgres.yaml
The Postgres database needs to be accessed only by Keycloak and Gitlab
in the same namespace. All other connections are forbidden.
/deploy
Close #1435
> feat: Add network policy to restrict access to Postgres.

- helm-chart/renku/templates/network-policies.yaml
- helm-chart/renku/templates/post-install-job-gitlab.yaml
This fix an issue introduced by #2613 resulting in the Post-install-gitlab
job not being able to access Postgres directly, which is needed.
> fix(networkpolicy) Grant post-install-gitlab job access to Postgres.

- helm-chart/renku/templates/network-policies.yaml
Empty descriptions cause the CI pipeline to fail.
> fix(network-policies) Fix the correct key for the Gitlab pod name.

- CHANGELOG.rst
- helm-chart/renku/Chart.yaml
- helm-chart/renku/values.yaml
Prepare new release with new minor version of GitLab to 14.10.5.
Merging this will upgrade dev's renku GitLab.
> chore: prep 0.14.1

- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/DatasetPage.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/ProjectPage.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/Datasets.scala
- helm-chart/renku/requirements.yaml
- helm-chart/renku/templates/NOTES.txt
- helm-chart/renku/templates/ingress.yaml
- helm-chart/renku/values.yaml
- helm-chart/values.yaml.changelog.md
- scripts/generate-values/base-renku-values.yaml.template
> feat: modify charts and tests for new UI release

- CHANGELOG.rst
- helm-chart/renku/Chart.yaml
This creates a version of 0.17 that can be deployed (0.17.0 contains a bug that was found after tagging but before deploying).
> chore: release 0.17.1

- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/JupyterNotebook.scala
The tests are timing out because they are trying to click the terminal icon and eventually succeed. But this takes ~ 45 mins.
I think the problem is that when the terminal is not found then whole page is reloaded and we look for the terminal again. But the sleeps in this process are not long enough to fully download assets and render stuff. But if we do not reload the page and keep retrying the page should just load eventually and the step should succeed.
> fix(tests): increase sleep for finding the terminal

- .scala-steward-config
We can use scala-steward to update dependencies in the acceptance tests. This config file tells scala-steward where the sbt project is located.
> chore: Add scala-steward config file

- CHANGELOG.rst
Tag a new release.
This includes only the bugfix for the gateway and documentation improvements. So it does not need a bigger version bump.
> chore: prep 0.18.2 release

- acceptance-tests/docker-run-tests.sh
Apparently, acceptance tests logs an error on tests sources formatting check. The statements look like follows:
```
[error] scalafmt: format all files; [git ls-files] (/tests): Failed to run command git rev-parse --show-toplevel. Error:
[error] > fatal: not a git repository (or any of the parent directories): .git
```
As this is a red herring it simply adds noise to the logs.
The reason scalafmt logs the error is its assumption that it's run inside a git repo. As tests sources are copied without the `.git` folder (tests sources live in a folder inside the renku repo) this requirement is not met. The fact is that the requirement does not prevent scalafmt to check formating correctly.
This PR simply workarounds the problem by initialising a git repo on the copied folder.
> chore: test formatting check not to raise an error in logs

- helm-chart/renku/values.yaml
This fixes a problem with nbconvert which is needed by jupyter server when it runs.
nbconver (a python package) was failing because of an unpinned dependency that it does not like. But nbconver does not explicitly mention this in their requirements. Otherwise this would not have happened.
> fix: update to latest project templates

- helm-chart/renku/requirements.yaml
- helm-chart/renku/templates/ingress.yaml
Forward /gitlab traffic to renku-traefik if external GitLab is used.
This should be merged at the same time as https://github.com/SwissDataScienceCenter/renku-gateway/pull/596, which configures Traefik to redirect /gitlab to the external GitLab URL, including the trailing relative path content if it exists.
#deploy /persist
> feat: redirect /gitlab to external GitLab url

- .github/workflows/check-acceptance-test-code.yml
This PR introduces a new GH action that checks if the Acceptance Tests code still compiles. The reason for the change is to have a smoke test that verifies if the tests are still OK after a dependencies update.
> test: GH action to verify tests compile

- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/KnowledgeGraphApi.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/Environments.scala
This PR addresses acceptance tests flakiness in cases when GET kg/status returns 400 straight after project creation.
> fix: AT to assume project not created on 400 from GET /status

- RELEASE.md
- acceptance-tests/build.sbt
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/KnowledgeGraphApi.scala
This PR brings some fixes to the acceptance tests around finding the status of events processing on the KG.
> fix: acceptance tests not to fail when getting event processing status

- RELEASE.md
Reflect that the release PRs for each deployment in terraform-renku are created automatically.
> docs: update YAT merge release process steps

- RELEASE.md
added a reminder to be transparent about outages and maintenance windows.
> chore(docs): update rollout/release wording

- .github/CODEOWNERS
- RELEASE.md
changes some codeowner around so we can enforce Changelog review by the product team and component updates by YAT.
This means no auto-pr can be merged without approval by the product team and YAT.
> chore: update codeowners to enforce auto-pr merge checks

- .github/dependabot.yml
- acceptance-tests/Dockerfile
- acceptance-tests/README.md
- acceptance-tests/requirements.txt
A few changes to make the acceptance tests a bit easier to use/run.
1. Updated the readme to indicate how to run the tests locally (and especially how to run only a specific test)
2. Moved the python packages used in the acceptance tests in a requirements.txt file
> chore(tests): use requirements.txt for python

- cypress-tests/cypress/e2e/publicProject.cy.ts
As far as I understand this test is failing because of issues with re-rendering in the ui.
I have recently tried to rerun this many times in the same PR without success.
So instead of keeping this flaky test around for no good reason I think it is much better to remove it until the underlying problem is solved. Then when the re-rendering issues are solved we can re-enable this.
> chore(tests): remove failing cypress test stage

- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/GraphStatus.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/GraphStatusSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/KnowledgeGraphApi.scala
Currently the structure returned from `/status` endpoint is being changed. The tests support old and new variants until the new version is everywhere.
> feat: Support the two different representation of graph status

- cypress-tests/cypress/e2e/publicProject.cy.ts
Try to prolong the timeout for indexing KG ti prevent early failures.
/deploy #persist #notest #cypress renku-ui=master
> test(cypress): fix KG activation timeout

- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/KnowledgeGraphApi.scala
This PR switches the LineageSpec to use the REST API instead of GraphQL that was recently removed
/deploy
> fix: lineage spec to use REST API instead of GraphQL

- helm-chart/renku/requirements.yaml
Updates the ca certificates injection to handle new java versions used by the KG.
Already tested at the BIT.
> chore: bump ca-certificates chart to 0.0.4

- .gitmodules
- helm-chart/renku/values.yaml
Had to bump python docs as well, they were still pointing to 1.x-lts
> chore: bump project templates and renku-python docs

- CHANGELOG.rst
- helm-chart/renku/requirements.yaml
Ignore the automated PR for the update. This has the version update and chagelog updates.
Rerun when the notebooks pipeline finally publishes the chart.
You can check the status of the renku notebooks publishing pipeline here: https://github.com/SwissDataScienceCenter/renku-notebooks/actions/runs/4323167717/jobs/7546472835
> chore: update renku notebooks to 1.15.1

- .github/workflows/pull-request-test.yml
- cypress-tests/cypress.config.ts
- cypress-tests/cypress/e2e/useSession.cy.ts
- cypress-tests/cypress/e2e/verifyInfrastructure.cy.ts
This PR extends the Cypress acceptance tests with a new test to verify that starting and terminating a session goes through the expected steps. There is also minimal interaction inside a JupyterLab environment.
This addresses the first part of #2852 but it doesn't tests workflows yet -- to be expanded.
/deploy #persist #notest #cypress
re #2852
> test(cypress): add session-specific test

- scripts/generate-ssh-host-keys/README.md
- scripts/generate-ssh-host-keys/generate-ssh-host-keys.py
- scripts/generate-ssh-host-keys/requirements.txt
This script can be used to generate the SSH host keys that can be optionally added to a Renkulab deployment when the SSH-into-session feature is enabled, so that they are persisted and the host key verification does not have to 
be performed again if Renku is re-deployed.
I have deployed in renku-dev the secret generated by this script and tested that I can still connect to my session.
> feat(scripts): Add script to generate SSH host keys secret.

- cypress-tests/cypress.config.ts
- cypress-tests/cypress/e2e/updateProjects.cy.ts
This PR refreshes the "Update Projects" tests by using v9 projects and trying an actual update.
/deploy #persist #notest #cypress
> test(cypress): use v9 and v10 projects for testing updates

- helm-chart/load-tests/.helmignore
- helm-chart/load-tests/Chart.yaml
- helm-chart/load-tests/templates/_helpers.tpl
- helm-chart/load-tests/templates/cronjob.yaml
- helm-chart/load-tests/templates/serviceaccount.yaml
- helm-chart/load-tests/values.yaml
- load-tests/.dockerignore
- load-tests/.gitignore
- load-tests/Dockerfile
- load-tests/README.md
- load-tests/chartpress.yaml
- load-tests/config.js
- load-tests/credentials.example.json
- load-tests/entrypoint.sh
- load-tests/scenarioCoreRequests.js
- load-tests/scenarioFileUpload.js
- load-tests/scenarioLecture.js
- load-tests/scenarioProjectMigration.js
- load-tests/utils/core.js
- load-tests/utils/general.js
- load-tests/utils/git.js
- load-tests/utils/oauth.js
- load-tests/utils/servers.js
This combines pre-existing load tests that existed mostly in the renku-python repo, puts them all in one place (here in this repo), updates the tests to use the chai-like describe/expect syntax and adds a helm chart for the load tests.
In addition to tests can be setup to publish their metrics to prometheus.
See existing metrics at https://grafana.dev.renku.ch. All metrics from k6 start with the name `k6`.
The idea is that the cronjob would run nightly on the dev cluster.
Once this is merged and the helm chart is published I will make a PR in the dev ops repo to deploy this. The existing results are only from running the tests a few times.
> chore: add load tests helm chart

- chartpress.yaml
- helm-chart/renku/Chart.yaml
- helm-chart/renku/requirements.yaml
- helm-chart/renku/templates/NOTES.txt
- helm-chart/renku/templates/_helpers.tpl
- helm-chart/renku/templates/_keycloak-clients-users.tpl
- helm-chart/renku/templates/configmap.yaml
- helm-chart/renku/templates/ingress.yaml
- helm-chart/renku/templates/keycloak-password-secret.yaml
- helm-chart/renku/templates/keycloak-postgres-secret.yaml
- helm-chart/renku/templates/network-policies.yaml
- helm-chart/renku/templates/post-install-job-keycloak.yaml
- helm-chart/renku/templates/secrets.yaml
- helm-chart/renku/values.yaml
This PR makes the change from the current `codecentric/keycloak` chart to the new `codecentric/keycloakx` chart. 
If the secrets for the deployment are managed by helm, make these changes _before_ you deploy this upgrade:
In the `keycloak-password-secret` secret, update keys to be: 
- `KEYCLOAK_USER` --> `KEYCLOAK_ADMIN`
- `KEYCLOAK_PASSWORD` --> `KEYCLOAK_ADMIN_PASSWORD`
In the `renku-keycloak-postgres` secret, update the keys to be:
- `DB_ADDR` --> `KC_DB_URL_HOST`
- `DB_DATABASE` --> `KC_DB_URL_DATABASE`
- `DB_USER` --> `KC_DB_USERNAME`
- `DB_PASSWORD` --> `KC_DB_PASSWORD`
If there are any custom keycloak values passed to helm, you need to change the `keycloak` namespace to `keycloakx`.
/deploy
> chore: upgrade from keycloak to keycloakx chart

- CHANGELOG-template.rst
- CHANGELOG.rst
- RELEASE.md
- docs/conf.py
Added a template for the `CHANGELOG.rst`, so it's clear how the changelog should be formatted, and you don't have to put together a hodgepodge of copy-pasting to assemble each new changelog entry.
Also fixed a small CHANGELOG formatting mishap I noticed, in which `0.24.0` had 2 "Internal Changes" sections.
> Add CHANGELOG-template.rst

- CHANGELOG.rst
Adds a blurb about why users should upgrade their base images.
> chore: update changelog for 0.25.0

- .gitignore
- acceptance-tests/.envrc
- acceptance-tests/flake.lock
- acceptance-tests/flake.nix
- acceptance-tests/local-run-test.sh
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/HandsOnSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/LineageSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/KnowledgeGraphApi.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/RestClient.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/Datasets.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/workflows/JupyterNotebook.scala
The status endpoint has been changed to require an access token. Thus to have acceptance tests work for new dev deployments, the access token must be given to the request.
Additionally fixes the stop condition when checking the status, the attempts were not incremented.
> fix: Add authorization cookies to graph/status requests

- .github/workflows/auto-reqs-update-pr.yml
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/model/commons.scala
- helm-chart/renku/templates/tests/test-renku.yaml
- helm-chart/renku/values.yaml
Needs https://github.com/SwissDataScienceCenter/renku-python/pull/3415 to properly work 
closes https://github.com/SwissDataScienceCenter/renku-python/issues/3402
allows setting something like `extra-values=global.renku.cli_version=2.4.0rc2` in auto-prs to test with a specific version (this is automatically set by CI with the changes in this PR)
> chore: change auto-pr action to create proper PR body for renku pre-releases

- .github/dependabot.yml
- chartpress.yaml
- scripts/init-realm/requirements.txt
Keycloak post install jobs have been failing; looks like it's an issue with old python-keycloak deps.
This PR bumps the python-keycloak version - testing to be performed by CI job.
> chore(deps): bump python-keycloak version in init-realm container from 0.24.0 to 2.14.0

- acceptance-tests/.scalafmt.conf
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/BatchProjectRemovalSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/model/commons.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/GitLabApi.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/KnowledgeGraphApi.scala
This PR modifies the existing `BatchProjectRemovalSpec` so it removes all the projects falling into the `test-(\d{4})-(\d+)-(\d+)-(\d+)-(\d+)-(\d+).*` pattern and are older than 7 days. To some extent, it's a complementary change to the one merged recently which started to skip project removal on test failure.
> feat: tests to remove test projects older than 7 days

- cypress-tests/cypress/e2e/publicProject.cy.ts
Temporarily disable checking the sentence `"This project is using the latest version of renku"` to prevent wrong results with candidate releases from renku-core.
This will be properly fixed one the new project's status section is ready on the UI (here is the reference PR: https://github.com/SwissDataScienceCenter/renku-ui/pull/2503 )
/deploy extra-values=global.renku.cli_version=2.4.1rc3 #persist #notest #cypress
> test(cypress): disable checking latest renku version

- helm-chart/renku/values.yaml
bumps the templates to new version to push out images with fixed toil path. 
> chore: bump template version

- CHANGELOG.rst
- helm-chart/renku/templates/gitlab-postgres-secret.yaml
- helm-chart/renku/templates/graph-db-postgres-secret.yaml
- helm-chart/renku/templates/graph-tg-postgres-secret.yaml
- helm-chart/renku/templates/graph-token-postgres-secret.yaml
- helm-chart/renku/values.yaml
I am not sure what is the logic behind the helm hooks for the secret creation.
But IMO it was needlessly complicated and it did not work when you upgrade from the helm chart version where the secret wasn't there.
So the changes I made are the following:
- removed the deletion hook because it was setting a value that is already the default
- made the hooks run before installing, upgrading or rolling back
This way the secret can be created when you are upgrading. Which was not the case before. 
I tested by deploying an older version and then upgrading. With this fix the secret is properly randomly created when you upgrade renku.
Because we have the logic to check if the secret exists (and not update it if it does) we can run the hook every time.
We have had similar discussions about this …
> fix(chart): generate db secrets on upgrade

- helm-chart/renku/templates/network-policies.yaml
Extends #3125 and is part of https://github.com/SwissDataScienceCenter/renku-graph/issues/1282.
This change is necessary so that the triple generator service can access Postgres.
> chore(chart): Add triples-generator to postgres-ingress network policy

- cypress-tests/cypress/e2e/verifyInfrastructure.cy.ts
Prevent running Cypress tests until KG returns a valid response.
/deploy #persist extra-values=global.renku.cli_version=2.6.0rc1
> test(cypress): check KG status properly before starting the tests

- scripts/init-realm/init-realm.py
- scripts/init-realm/requirements.txt
This merge request does several small improvements:
- Fixes a warning that will turn into an error when python-keycloak 4 will be out
- Improves the warning message when something goes wrong adding the status code so one can know what might be happening
- Bump the python-keycloak version to the latest release at the time of writing (3.3.0)
The last point goes beyond what is proposed in #3066 and this pull request can be used in place of it.
In any case, the python-keycloak bump is required as the current release of `init-realm` (0.29.0) fails to generate the realms and clients due to an internal error in the python-keycloak version used.
> Improve realm init

- CHANGELOG.rst
- docs/how-to-guides/admin/prerequisites/certificates.rst
- helm-chart/renku/templates/ingress.yaml
- helm-chart/renku/values.yaml
- helm-chart/values.yaml.changelog.md
This merge request has the following aims:
- Make the ingress class selection follow current best practice
- Allow the deployment with and without cert-manager
- Improve the documentation related to certificate handling
The updated documentation provides now an example that developers can use to test-drive Renku using https.
> Improve ingress handling

- docs/conf.py
This updates the year in the docs and removes the authors which are hard to maintain and don't show up anywhere.
> chore: update date and remove unused authors

- .github/workflows/pull-request-test.yml
- cypress-tests/cypress/e2e/privateProject.cy.ts
- cypress-tests/cypress/e2e/publicProject.cy.ts
- cypress-tests/cypress/support/commands/projects.ts
Add Cypress tests to cover private projects and test visibility.
fix https://github.com/SwissDataScienceCenter/renku/pull/3216
/deploy #persist #cypress #notest
> test(cypress): add test for private projects and visibility

- cypress-tests/config.ts
- cypress-tests/cypress.config.ts
- cypress-tests/cypress/e2e/privateProject.cy.ts
- cypress-tests/cypress/e2e/publicProject.cy.ts
- cypress-tests/cypress/e2e/testDatasets.cy.ts
- cypress-tests/cypress/e2e/updateProjects.cy.ts
- cypress-tests/cypress/e2e/useSession.cy.ts
- cypress-tests/cypress/support/commands/datasets.ts
- cypress-tests/cypress/support/commands/projects.ts
This should fix a couple of recurring problems with Cypress tests:
- Metadata indexing doesn't necessarily start immediately.
- Using the search page frequently fails.
/deploy
> test(cypress): improve stability

- .github/workflows/cron-jobs.yaml
It's not needed anymore since we configure the retention days separately.
> ci: remove the job to clean up old artifacts

- helm-chart/renku/requirements.yaml
This PR brings a graph update to `2.42.1` instead of `2.42.0`. It was simply missed in the relevant upgrade PR (#3255).
The changelog has been updated to `2.42.1` already in the mentioned PR.
Sorry for the confusion.
/deploy
> chore: update graph to 2.42.1

- CHANGELOG.rst
- helm-chart/renku/values.yaml
The gateway helm chart did not have a default value set for this. But the default value was set in the renku helm chart. When I was combining the helm charts I copied over the values from the component charts into Renku. And when I did this I removed the default we had set for this in the renku chart.
This puts it back. 
For example if you go to https://github.com/SwissDataScienceCenter/renku/blob/0.38.0/helm-chart/renku/values.yaml#L41 you will see it. 0.38.0 is the last version before we combined the helm charts.
> fix(chart): default value for client ID in Gitlab

- CHANGELOG.rst
- docs/spelling_wordlist.txt
- helm-chart/renku/templates/notebooks/network-policy.yaml
- helm-chart/renku/templates/notebooks/statefulset.yaml
- helm-chart/renku/templates/notebooks/test.yaml
This is the result of the helm chart consolidation.
We did not see this because the problems that this solves do not appear in CI deployments or are not obvious in CI deployments.
/deploy
> fix(chart): session network policies, tolerations and affinities

- CHANGELOG.rst
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/ImportZenodoWithCliSpec.scala
- acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/BddWording.scala
- helm-chart/renku/values.yaml
This PR upgrades graph to `2.43.1` and temporarily tags the Zenodo acceptance test with `ignore` until the problem on Zenodo side is resolved.
/deploy
> chore: graph 2.43.1

- CHANGELOG.rst
- helm-chart/renku/values.yaml
Update UI to version 3.14.0
/deploy extra-values=dataService.image.pullPolicy=Always,global.gitlab.url=https://gitlab.dev.renku.ch,notebooks.cloudstorage.s3.enabled=true,amalthea.extraChildResources[0].group=com.ie.ibm.hpsys,amalthea.extraChildResources[0].name=datasets,notebooks.cloudstorage.s3.installDatashim=false
> chore: update UI to version 3.14.0

- CHANGELOG.rst
- helm-chart/renku/values.yaml
- helm-chart/values.yaml.changelog.md
This includes the changelog changes from https://github.com/SwissDataScienceCenter/renku/pull/3329
/deploy extra-values=global.gitlab.url=https://gitlab.dev.renku.ch
> chore: upgrade data services to 0.2.0

- helm-chart/renku/values.yaml
This was accidentally removed in the chart refactoring.
> chore: restore contributed project templates ref

- docs/how-to-guides/admin/gitlab.rst
- helm-chart/renku/templates/_helpers.tpl
- helm-chart/renku/templates/gateway/deployment-revproxy.yaml
- helm-chart/renku/templates/graph/commit-event-service-deployment.yaml
- helm-chart/renku/templates/graph/event-log-deployment.yaml
- helm-chart/renku/templates/graph/knowledge-graph-deployment.yaml
- helm-chart/renku/templates/graph/token-repository-deployment.yaml
- helm-chart/renku/templates/graph/triples-generator-deployment.yaml
- helm-chart/renku/templates/graph/webhook-service-deployment.yaml
- helm-chart/values.yaml.changelog.md
This PR changes relevant renku Helm chart config files so `global.gitlab.url` in used instead of `graph.gitlab.url`.
/deploy
> chore: graph services to use global.gitlab.url

- CHANGELOG.rst
- helm-chart/renku/templates/swagger.yaml
- helm-chart/renku/values.yaml
Updates data-service to resolve a bug that was released in 0.20.0. This bugfix includes the fix from master which excludes service links from the environment in the swagger container. 
/deploy
> chore: bump data-service version for 0.41.1 bugfix release

- acceptance-tests/src/test/scala/ch/renku/acceptancetests/model/commons.scala
- helm-chart/renku/templates/tests/test-renku.yaml
This PR:
* fixes a bug in the selenium tests around commit sha extraction from the non-release CLI version
* removes setting up the `RENKU_CLI_VERSION` env variable for the selenium tests so the version fetched from the Core is used.
/deploy
> fix: selenium tests to use CLI in version from Core

- helm-chart/renku/requirements.yaml
This PR upgrades Jena to `4.10.0` through renku-jena chart `0.22.0`.
/deploy
> chore: jena upgraded to 4.10.0

- .devcontainer/devcontainer.json
Java is needed since we are running plantuml locally. To build docs, go to docs directory and do `make html`.
> chore: add java to devcontainer

- docs/how-to-guides/own_machine/cli-installation.rst
Following the recommended way to configure the PATH variable for pipx : https://github.com/pypa/pipx#install-pipx
> docs: configures pipx path according to documentation

- CHANGELOG.rst
- docs/how-to-guides/admin/gitlab.rst
- helm-chart/renku/templates/_helpers.tpl
- helm-chart/renku/templates/gateway/deployment-revproxy.yaml
- helm-chart/renku/templates/graph/commit-event-service-deployment.yaml
- helm-chart/renku/templates/graph/event-log-deployment.yaml
- helm-chart/renku/templates/graph/knowledge-graph-deployment.yaml
- helm-chart/renku/templates/graph/token-repository-deployment.yaml
- helm-chart/renku/templates/graph/triples-generator-deployment.yaml
- helm-chart/renku/templates/graph/webhook-service-deployment.yaml
- helm-chart/renku/values.yaml
- helm-chart/values.yaml.changelog.md
This deploys the fix for the following bugs found in 0.42.0:
/deploy
> chore: update data service - prep 0.42.1

- helm-chart/renku/values.yaml
@leafty found that the default value for this in the Keycloak helm chart is 100.\
/deploy
> chore: set keycloak max db connections to 10

- CHANGELOG.rst
- helm-chart/renku/values.yaml
✨ Introduce a revamped landing page.
Fixes https://github.com/SwissDataScienceCenter/renku/issues/3357.
/deploy extra-values=global.renku.cli_version=2.7.0 #persist
>  feat: introduce a redesigned landing page

- .github/workflows/pull-request-test.yml
Allows the PR to be merged even when tests are skipped.
> chore: skip individual cypress steps

- .github/workflows/pull-request-test.yml
This add a "View deployment" button on the deployment box in PRs which links to the deployment.
Other changes are formatting changes (from "Format on save" in vscode).
/deploy #notest
> chore: make the deploy action report the URL

- cypress-tests/cypress/e2e/checkWorkflows.cy.ts
- cypress-tests/cypress/support/commands/general.ts
Rewrite the `checkWorkflows` test to use a more descriptive and more robust action to follow the "Default input" link.
See also: https://github.com/SwissDataScienceCenter/renku-ui/pull/3022.
/deploy
> fix(cypress): fix the checkWorkflows test

- helm-chart/renku/requirements.yaml
/deploy extra-values=notebooks.cloudstorage.enabled=true,notebooks.cloudstorage.storageClass=csi-rclone-test-liveness,global.csi-rclone.install=true,csi-rclone.storageClassName=csi-rclone-test-liveness,csi-rclone.csiNodepluginRclone.tolerations[0].key=renku.io/dedicated,csi-rclone.csiNodepluginRclone.tolerations[0].operator=Equal,csi-rclone.csiNodepluginRclone.tolerations[0].value=user,csi-rclone.csiNodepluginRclone.tolerations[0].effect=NoSchedule
> chore: bump csi-rclone

- .github/workflows/publish-helm-chart.yml
Going forward @yat will rely on Renovate to create a PR in `terraform-renku` that updates the version of Renkulab.
> chore: remove Github action that opens PRs in `terraform-renku` to update Renkulab.

- .github/workflows/auto-reqs-update-pr.yml
Disables automatic creation of PRs but keeps as a dispatch trigger in case we still want to use some of the functionality.
> chore: disable automatic PRs

- helm-chart/renku/values.yaml
This change to the values files of Solr enables a network policy to Solr such that only `search-api` and `search-provision` are allowed to connect to it.
/deploy
> feat: enable NetPol for Solr.

- CHANGELOG.rst
- helm-chart/renku/requirements.yaml
- helm-chart/renku/values.yaml
This PR:
* upgrades renku-graph to `2.50.0`
* upgrades Jena to `5.0.0`
/deploy
> chore: renku-graph 2.50.0 (with Jena 5.0.0)

- CHANGELOG.rst
Update the release note with changes coming from `renku-ui` and Renku 2.0 sessions (UI, notebooks, data services).
> chore: update changelog for release 0.50.0

- docs/how-to-guides/admin/prerequisites/certificates.rst
The current version shows the configuration at the top level of the yaml while it should be under the global scope.
More details about the global scope in the [helm documentation](https://helm.sh/docs/chart_template_guide/subcharts_and_globals/).
> doc: improve the custom CA configuration part

- CHANGELOG.rst
- helm-chart/renku/templates/data-service/deployment.yaml
- helm-chart/renku/templates/data-service/service.yaml
- helm-chart/renku/values.yaml
/deploy extra-values=dataService.sentry.enabled=true,dataService.sentry.dsn=https://e47c95d665684bce89984bd4595268df@sentry.dev.renku.ch/13,dataService.sentry.environment=ci-renku-3548,dataService.sentry.sampleRate=0.5
> chore: add sentry and prometheus for data services

- helm-chart/renku/requirements.yaml
`bitnami/common` is used in several places and can cause version conflicts.
> chore: set bitnami-common version in the parent chart

- cypress-tests/cypress/support/commands/sessions.ts
The check for the stopping button to be visible after stopping a session causes flakiness since the session can be removed very quickly, in which case the button is never shown.
> Skip stopping button check

- .github/workflows/cron-jobs.yaml
- .github/workflows/publish-helm-chart.yml
- .github/workflows/publish-master-merges.yaml
- .github/workflows/pull-request-test.yml
- .github/workflows/renku-dev-test.yaml
- cypress-tests/cypress/e2e/checkWorkflows.cy.ts
- cypress-tests/cypress/e2e/privateProject.cy.ts
- cypress-tests/cypress/e2e/publicProject.cy.ts
- cypress-tests/cypress/e2e/rstudioSession.cy.ts
- cypress-tests/cypress/e2e/testDatasets.cy.ts
- cypress-tests/cypress/e2e/updateProjects.cy.ts
- cypress-tests/cypress/e2e/useSession.cy.ts
- cypress-tests/cypress/support/commands/general.ts
- cypress-tests/cypress/support/commands/login.ts
- cypress-tests/cypress/support/commands/projects.ts
- cypress-tests/package-lock.json
I think the reason for the failures when things run in parallel is that the tests do not wait sufficiently long for the redirects of the login process to finish. And they try to visit a page before the user has fully logged in.
Hopefully the check of the url after the login process finishes is enough to remedy this. 
/deploy
The changes that helped are:
- Adding a wait right after the login completes, for some reason the main problem was that after the login was complete calling gitlab still randomly resulted in 401s half the time. But after waiting for 10s Gitlab does not respond with 401s.
- Removing the login from the before hook and adding it to every beforeEach hook. I did the same with the project creation. This is better because beforeEach hooks are retried where as a single …
> fix: parallel cypress tests

- CHANGELOG.rst
- helm-chart/renku/values.yaml
Steven from the academic team encountered this issue.
With the update of the notebook service to handle multiple repos the path where the project is cloned was set to a different parameter from gitlab which seems to ignore the case of the letter in the name. But a lot of other parameters - most important of which is the working directory for the session - was set to the case sensitive value from gitlab.
This resulted in projects which have a path with upper and lowercase letters to be cloned in the wrong directory.
For more info see the PR in the notebook service.
/deploy
> fix: cloning repositories in sessions

- CHANGELOG.rst
- helm-chart/renku/values.yaml
`renku-notebooks` bugfix release 1.25.1 brings in the following fixes:
* fix: do not add storage mounts patches when a session has no repository ([#1892](https://github.com/SwissDataScienceCenter/renku-notebooks/pull/1892))
/deploy
> fix: update renku-notebooks to 1.25.1

- RELEASE.md
Now that we use ShapeUp to organize most of the work within the Renku Team, we might want to expand the guidelines for releasing to optimize the process and prevent conflicts between different features.
> docs: update release file

- CHANGELOG.rst
- helm-chart/renku/templates/search/search-api-deployment.yaml
- helm-chart/renku/values.yaml
- helm-chart/values.yaml.changelog.md
The search verifies JWT tokens using the pulbic key from their issuer. A setting can be specified which urls are expected issuers.
> fix: Allow to configure jwt issuer urls for search-api

- CHANGELOG.rst
- helm-chart/renku/values.yaml
Fixes a bug where group members cannot access all projects that are part of the group because the group permissions did not fully cascade to projects.
/deploy
> fix: upgrade renku data service to 0.15.1

- CHANGELOG.rst
- helm-chart/renku/requirements.yaml
Addresses a bug where Amalthea would not start when prometheus metrics or the audit log export functionality is enabled.
> release 0.56.1

- CHANGELOG.rst
- helm-chart/renku/requirements.yaml
This fixes an error where the new version of the csi rclone was failing when a secret annotation was not used to define the secret. This was supposed to work but the storage class that is marked to use the PVC annotation will fail if the annotation is not present. So we had to use 2 storage classes one that requires a PVC annotation for the secret and another that is the same as the current one - which expects that the PVC name and secret is the same.
> fix: bump csi rclone to 0.3.1

- CHANGELOG.rst
- helm-chart/renku/values.yaml
Fixes the `Authorization` header for the Renku 2.0 search service.
/deploy
> fix: bump gateway to 1.0.2

- CHANGELOG.rst
- helm-chart/renku/values.yaml
Gateway: fix getting HTTP error 500 when logging in.
/deploy
> fix: bump renku-gateway to 1.0.3

- cypress-tests/cypress/e2e/useSession.cy.ts
Used to fix acceptance tests in https://github.com/SwissDataScienceCenter/renku-notebooks/pull/1984.
/deploy
> fix: renku-jupyterserver logged out in session tests

- docs/how-to-guides/admin/gitlab.rst
Following the release of the new API Gateway, the redirect URLs configuration for external GitLab instances needs to be updated.
> fix: update admin documentation on GitLab

- CHANGELOG.rst
The "individual components" section went lost when solving the conflicts before merging
> docs: fix changelog

- CHANGELOG.rst
- helm-chart/renku/values.yaml
> feat: update data service to 0.21.0

- CHANGELOG.rst
* note the search fix in the user facing changes section
* some minor wordsmithing
> add search fix to user facing changes

- CHANGELOG.rst
- helm-chart/renku/values.yaml
See: https://github.com/SwissDataScienceCenter/renku-ui/issues/3350.
Fixes permission check in the Renku 2.0 UI. Notably, group owners can update projects in the group even if they are not direct project members.
/deploy
> fix: update permission checks in Renku 2.0

- CHANGELOG.rst
- helm-chart/renku/values.yaml
Fixes a bug with data connectors where typing a slug would not be taken into account and using uppercase letter in the name would cause issues.
/deploy
> fix: bump renku-ui to 3.40.1

- CHANGELOG.rst
- helm-chart/renku/values.yaml
Fixes an issue where project editors could not edit projects in Renku 2.0 (from the "General Settings" form).
/deploy
> fix: bump data-services to 0.24.2

- CHANGELOG.rst
- helm-chart/renku/requirements.yaml
- helm-chart/renku/templates/data-service/deployment.yaml
- helm-chart/renku/templates/notebooks/deployment.yaml
- helm-chart/renku/templates/notebooks/env-secret.yaml
- helm-chart/renku/values.yaml
> fix: various amalthea, helm chart and data service fixes

- CHANGELOG.rst
- helm-chart/renku/requirements.yaml
> chore: update redis helm chart to latest revision

- CHANGELOG.rst
- helm-chart/renku/templates/network-policies.yaml
- helm-chart/renku/values.yaml
Closes #3832.
Add support for session secret slots and session secrets in Renku 2.0.
/deploy
> feat: add support for session secrets in Renku 2.0

- CHANGELOG.rst
- helm-chart/renku/values.yaml
This PR introduces the following updates:
- Early Access: Implements changes to enable early access to Renku 2.0
- Disk Storage Configuration in Renku 2.0 sessions 
- Fix hide the edit button when the user does not have permissions
- Fix show all data connector password fields 
/deploy
> chore: update renku-ui to 3.46.0 and renku-data-services to 0.31.0

- .github/workflows/pull-request-test.yml
- cypress-tests/cypress/e2e/v2/dashboardV2.cy.ts
- cypress-tests/cypress/e2e/v2/projectBasics.cy.ts
- cypress-tests/cypress/support/commands/general.ts
- cypress-tests/cypress/support/commands/login.ts
- cypress-tests/cypress/support/types/project.types.ts
- cypress-tests/cypress/support/types/user.types.ts
- cypress-tests/cypress/support/utils/projectsV2.utils.ts
See title
/deploy renku-ui=lorenzo/cypress-renku-2.0-data-cy
fix #3880
> Add a cypress test for testing project basic operations: create, edit, delete

- CHANGELOG.rst
- helm-chart/renku/requirements.yaml
Updates the CSI rclone helm chart to fix an issue with restarting liveness probes on the rclone daemonset pods.
> fix: update csi rclone to 0.3.6

- cypress-tests/cypress/e2e/v2/groupBasics.cy.ts
- cypress-tests/cypress/e2e/v2/projectBasics.cy.ts
This fixes the projectBasics and groupBasics tests logic on projects/groups creation and deletion to avoid possible collisions when tests fail and re-run.
/deploy renku-ui=lorenzo/cypress-renku-2.0-data-cy
> test: fix projectBasics and groupBasics

- cypress-tests/README.md
This refreshes the README file for the Cypress tests:
- Add a `Test coverage` section to state more clearly what the tests are meant to achieve.
- Adjust the text about how to run the tests.
- Refresh the section on the CI integration -- a few things changed in how we handle that.
> docs: update the cypress tests readme file

- .github/workflows/pull-request-test.yml
This will simplify making v2 tests mandatory and v1 optional
/deploy renku-ui=main
> ci: split v2 and legacy Cypress tests

- CHANGELOG.rst
- helm-chart/renku/templates/notebooks/deployment.yaml
- helm-chart/renku/values.yaml
- helm-chart/values.yaml.changelog.md
This turns off the notebook service and uses the data service to manage JupyterServers.
/deploy
I tested in another throwaway CI deployment that when we update the sessions from v1 and v2 sessions are still visible to users. For both registered and anonymous users.
> feat: turn off notebook service

- CHANGELOG.rst
- helm-chart/renku/values.yaml
Enable migrate project with private images from the Renku Gitlab registry  from Renku V1 to Renku 2.0
/deploy #legacy
> feat: enable migrate project with private images from the Renku Gitlab registry

- helm-chart/renku/values.yaml
I am opening this to target `master` as its something needed by CI
deployments mostly.
Let me know if I should rather target the release, but it should be
merged sooner rather than later.
> fix: Increase default resources for Search containers.

- CHANGELOG.rst
- helm-chart/renku/requirements.yaml
- helm-chart/renku/values.yaml
Add support for using published datasets hosted on InvenioRDM (including Zenodo) and Dataverse as global data connectors.
Global data connectors do not belong to any namespace and can be modified by admins only. As a special case, data connectors of type DOI can be added by logged in users.
Contents:
* https://github.com/SwissDataScienceCenter/renku-data-services/pull/823
* https://github.com/SwissDataScienceCenter/renku-ui/pull/3656
* https://github.com/SwissDataScienceCenter/rclone/pull/7
* https://github.com/SwissDataScienceCenter/csi-rclone/pull/53
Demo: https://ci-renku-3971.dev.renku.ch/v2/projects/flora.thiebaut/demo-project
/deploy extra-values=global.csi-rclone.install=true,notebooks.cloudstorage.enabled=true,notebooks.cloudstorage.storageClass=csi-rclone-doi-zenodo,csi-rclone.sto …
> feat: support published datasets with global data connectors

- CHANGELOG.rst
- helm-chart/renku/templates/data-service/deployment_data_tasks.yaml
- helm-chart/renku/templates/network-policies.yaml
- helm-chart/renku/values.yaml
Adds configuration for the data tasks deployment. This runs background tasks in the scope of data services in one python runtime.
/deploy
> feat: Add data tasks deployment

- CHANGELOG.rst
- helm-chart/renku/values.yaml
Update renku-ui to 3.55.0, which includes:
- Card design for session launchers and sessions on the project page.
- Support for migrating projects from Renku v1 to Renku 2.0.
- Session UX improvements.
/deploy
> feat: update renku UI 3.35.0

- CHANGELOG.rst
The bug I removed from the changelog is new. It was introduced and fixed as part of this release and users never saw it because it was never released. So we do not have to mention it in the changelog.
> chore: update changelog

- CHANGELOG.rst
- helm-chart/renku/requirements.yaml
- helm-chart/renku/values.yaml
/deploy extra-values=global.csi-rclone.install=true,notebooks.cloudstorage.enabled=true,notebooks.cloudstorage.storageClass=csi-rclone-doi-zenodo,csi-rclone.storageClassName=csi-rclone-doi-zenodo,global.rcloneStorageClass=csi-rclone-doi-zenodo,amalthea-sessions.rcloneStorageClass=csi-rclone-doi-zenodo-secret-annotation,csi-rclone.csiNodepluginRclone.tolerations[0].key=renku.io/dedicated,csi-rclone.csiNodepluginRclone.tolerations[0].operator=Equal,csi-rclone.csiNodepluginRclone.tolerations[0].value=user,csi-rclone.csiNodepluginRclone.tolerations[0].effect=NoSchedule,csi-rclone.csiNodepluginRclone.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].key=renku.io/node-purpose,csi-rclone.csiNodepluginRclone.affinity.nodeAffinity.required …
> feat: bump csi-rclone and renku-data-services

- .github/CODEOWNERS
- .github/release-drafter.yml
- .github/workflows/create-release-branch.yml
- CHANGELOG.rst
- docs/spelling_wordlist.txt
The draft release is here: https://github.com/SwissDataScienceCenter/renku/releases/tag/untagged-afcb7c821b481c8f4c4b
The discussion is here: https://www.notion.so/renku/Release-0-70-0-1eb0df2efafc8018a2d3c73101a3f345?pvs=4
> chore: use github releases

- helm-chart/renku/requirements.yaml
Support for rclone v.169.3+renku-1 which fixes an issue with Zenodo datasets which have virtual subfolders.
Note: `renku-data-services` is NOT updated, but the patch version mismatch should not cause issues.
/deploy #legacy extra-values=global.csi-rclone.install=true,notebooks.cloudstorage.enabled=true,notebooks.cloudstorage.storageClass=csi-rclone-doi-zenodo,csi-rclone.storageClassName=csi-rclone-doi-zenodo,global.rcloneStorageClass=csi-rclone-doi-zenodo,amalthea-sessions.rcloneStorageClass=csi-rclone-doi-zenodo-secret-annotation,csi-rclone.csiNodepluginRclone.tolerations[0].key=renku.io/dedicated,csi-rclone.csiNodepluginRclone.tolerations[0].operator=Equal,csi-rclone.csiNodepluginRclone.tolerations[0].value=user,csi-rclone.csiNodepluginRclone.tolerations[0].effect=NoSchedule,csi-rclone.c …
> feat: bump csi-rclone

- helm-chart/renku/templates/_certificates-init-container.tpl
- helm-chart/renku/templates/authz/deployment.yaml
- helm-chart/renku/templates/setup-job-authz-db.yaml
- helm-chart/renku/templates/setup-job-keycloak-db.yaml
- helm-chart/renku/templates/setup-job-keycloak-realms.yaml
- helm-chart/renku/templates/setup-job-platform-init.yaml
- helm-chart/renku/templates/setup-job-renku-dbs.yaml
- helm-chart/renku/templates/tests/test-renku.yaml
- helm-chart/renku/templates/ui/ui-client-deployment-template.yaml
- helm-chart/renku/templates/ui/ui-server-deployment.yaml
- helm-chart/renku/values.yaml
- helm-chart/values.yaml.changelog.md
This patch harmonizes the handling/configuration of the securityContext field through all the templates.
Its content was defined in multiple different manifests. Being hard coded there made them unsuitable for modifications such as required for OpenShift deployment.
They now all use the content coming from the values file since they were mostly all using the same values.
> refactor: harmonize security context handling

- helm-chart/renku/templates/swagger.yaml
- helm-chart/renku/values.yaml
Change the swagger template so that the image can also be configured when deploying Renku.
This allows to customize swagger in the same way as other components.
Useful for example when deploying on OpenShift where the default image cannot run due to security constraints.
> feat: make swagger-ui image configurable

- helm-chart/renku/templates/swagger.yaml
By default, we still load the renku-python "core" service as default when opening Swagger, although we mostly use the data services now.
This change makes Data Service the default selected service.
P.S. We might want to remove some entries from the list -- probably Notebooks and Search?
/deploy
> chore: swap swagger services order to show data service first

- cypress-tests/cypress/e2e/v2/groupBasics.cy.ts
- helm-chart/renku/values.yaml
Some bugfixes and:
+ New group search tab.
+ Disable V1 on-demand.
https://github.com/SwissDataScienceCenter/renku-ui/releases/tag/4.4.0
This includes a minor update to the acceptance tests
/deploy
> feat: update renku-ui to 4.4.0

- docs/docusaurus.config.ts
Docusaurus wants the url and the path to be separated. But read the docs shoves this into one url. This way we parse and split them up and use them in the right place.
Here is the output from the failed read the docs build:
```
npm --prefix docs run build
> docs@0.0.0 build
> docusaurus build
[ERROR] Error: The url is not supposed to contain a sub-path like "/en/latest/". Please use the baseUrl field for sub-paths.
at validateConfig (/home/docs/checkouts/readthedocs.org/user_builds/renku/checkouts/latest/docs/node_modules/@docusaurus/core/lib/server/configValidation.js:372:15)
at loadSiteConfig (/home/docs/checkouts/readthedocs.org/user_builds/renku/checkouts/latest/docs/node_modules/@docusaurus/core/lib/server/config.js:40:62)
at async Promise.all (index 1)
at async loadContext …
```
> chore: fix read the docs build

- helm-chart/renku/requirements.yaml
Changes the order of the proxies so that sessions where the base URL path is stripped to "/" still works.
/deploy
> fix: upgrade amalthea to 0.20.1

- helm-chart/renku/templates/ui/ui-client-deployment-template.yaml
- helm-chart/renku/values.yaml
- helm-chart/values.yaml.changelog.md
Add a new value `ui.client.supportLegacySessions` to turn off the Legacy sessions on the UI side -- see [lorenzo/v1-sessions-warnings](https://github.com/SwissDataScienceCenter/renku-ui/pull/3789)
This PR includes the latest UI version 4.6.0 with a bunch of other minor improvements and bugfixes
/deploy extra-values=ui.client.supportLegacySessions=false
> feat: prepare Legacy sessions phase out

- acceptance-tests/Dockerfile
It seems the debian version in the python 3.9 slim image got updated. And that means the java version we were using is not available anymore and the apt-key command is depracated.
I tested, reproduced and fixed this locally.
> fix: scala installation in Helm test docker image

- minimal-deployment/minimal-deployment-values.yaml
This makes CI deployments of Renku use Redis in standalone mode. Which cuts down 2 redis instances (which are not small).
/deploy
> chore(ci): deploy Redis in standalone mode

- .github/workflows/build-global-renkulab-images.yml
Dependabot PRs cannot push the images so we can use renkubot's account to get around it
> chore: use renkubot to push images

- minimal-deployment/minimal-deployment-values.yaml
The values are just based on running `kubectl top pods` on a random but relatively recent CI deployment.
/deploy
> chore: update resource in minimal deployment values

- minimal-deployment/minimal-deployment-values.yaml
@leafty reported restarts when trying to run migrations from a shell from inside the data service. This should work without restarting for CI deployments.
> chore(ci): increase memory for the data service

- helm-chart/renku/requirements.yaml
- minimal-deployment/minimal-deployment-values.yaml
To avoid running into CI deployment issues with the [forthcoming changes to the Bitnami catalogue](https://github.com/bitnami/charts/issues/35164), this PR modifies the Renku Helm chart to pull the relevant Bitnami Helm charts and Docker images from Renkulab.io's Harbor instance instead of from Bitnami.
/deploy
> chore(helm-chart): use harbor-hosted bitnami artifacts

- helm-chart/renku/requirements.yaml
Upgrades amalthea to make sure the bitnami image deprecation does not break sessions.
/deploy
> release 2.7.1

- .github/workflows/build-global-renkulab-images.yml
- global-images/Makefile
- global-images/README.md
dependabot was actually not able to push because it does not have access to repo secrets; use the explicit token permissions instead.
> chore: modify token permissions on image build
